using Hangfire;
using Microsoft.Extensions.Logging;
using Rafiq.Application.Common.Interfaces;
using Rafiq.Domain.Enums;
using Rafiq.Domain.Repositories;
using Rafiq.Application.VoiceAgent.Agent;

namespace Rafiq.Infrastructure.Services.BackgroundJobs;

/// <summary>
/// Hangfire fire-and-forget job that runs the shared agent loop for Chat messages.
/// Survives app restarts because Hangfire persists jobs in SQL Server.
/// Completes even if the browser tab that triggered the request is closed or refreshed.
/// </summary>
public sealed class ChatMessageProcessorJob(
    IAiConversationRepository conversationRepository,
    VoiceAgentLoop agentLoop,
    INotificationService notificationService,
    IUnitOfWork unitOfWork,
    IBackgroundUserContext backgroundUserContext,
    ILogger<ChatMessageProcessorJob> logger)
{
    // No automatic retries — a failed AI call should show the user an error message,
    // not re-run the same prompt silently hours later.
    [AutomaticRetry(Attempts = 0)]
    public async Task ExecuteAsync(
        Guid userId,
        Guid conversationId,
        Guid assistantMessageId,
        string userText,
        string? base64Image,
        string? imageFormat)
    {
        // Inject user identity for any downstream service that reads ICurrentUserService.
        backgroundUserContext.UserId = userId;

        var userIdStr = userId.ToString();
        logger.LogInformation(
            "ChatMessageProcessorJob started for conversation={ConvId}, assistantMessage={MsgId}",
            conversationId, assistantMessageId);

        var session = await conversationRepository.GetWithMessagesAsync(
            conversationId, userId, CancellationToken.None);

        if (session is null)
        {
            logger.LogWarning("Conversation {ConvId} not found. Aborting.", conversationId);
            return;
        }

        // Find the placeholder assistant message we need to fill in.
        var assistantMsg = session.Messages.FirstOrDefault(m => m.Id == assistantMessageId);
        if (assistantMsg is null)
        {
            logger.LogWarning("Assistant placeholder {MsgId} not found. Aborting.", assistantMessageId);
            return;
        }

        // Mark as Processing so the UI can distinguish "waiting to start" from "running".
        assistantMsg.SetProcessing();
        await unitOfWork.SaveChangesAsync(CancellationToken.None);

        // Build history for the agent loop.
        // SendMessageCommandHandler already persisted BOTH the current user message
        // (seq = placeholderSeq - 1) AND the assistant placeholder (seq = placeholderSeq).
        // VoiceAgentLoop.RunAsync will re-append the user message from `userText`, so we
        // MUST exclude it here — otherwise Bedrock sees two consecutive user messages
        // and either rejects the request or (worse) responds with a bare final answer
        // like "تم إضافة الموعد" without ever calling the write tool.
        var placeholderSeq = assistantMsg.SequenceNumber;
        var existingHistory = session.Messages
            .Where(m => m.SequenceNumber < placeholderSeq - 1)
            .OrderBy(m => m.SequenceNumber)
            .Select(m => (m.Role, m.Content))
            .ToList();

        var nowUtc = DateTime.UtcNow;
        var ctx = new AgentContext(
            UserId: userId,
            ProfileId: session.UserHealthProfileId,
            SessionId: session.Id,
            Language: "en",
            Today: DateOnly.FromDateTime(nowUtc),
            NowUtc: nowUtc,
            UtcOffsetMinutes: 0);

        try
        {
            var (output, newLoopMessages) = await agentLoop.RunAsync(
                userText,
                existingHistory,
                ctx,
                systemPromptOverride: null,
                base64Image: base64Image,
                imageFormat: imageFormat,
                CancellationToken.None);

            // Determine the final text from the loop output.
            var finalText = output switch
            {
                FinalAnswer fa => fa.Response,
                AskUser au    => au.Question,
                _             => string.Empty
            };

            // Persist all intermediate messages (tool calls, tool results) generated by the loop.
            // The placeholder assistant message is NOT in newLoopMessages — it was created before
            // the loop. Persist the intermediates with fresh sequence numbers.
            var nextSeq = (session.Messages.Max(m => m.SequenceNumber)) + 1;
            foreach (var (role, content) in newLoopMessages)
            {
                // Skip the final assistant message — it updates the placeholder instead.
                if (role == AiMessageRole.Assistant && content == finalText) continue;
                await conversationRepository.AddMessageAsync(
                    new Domain.Entities.Chat.AiMessage(session.Id, role, content, nextSeq++),
                    CancellationToken.None);
            }

            // Complete the placeholder with the final answer.
            assistantMsg.Complete(!string.IsNullOrWhiteSpace(finalText) ? finalText : "…");
            session.MarkMessageActivity(DateTime.UtcNow);
            await unitOfWork.SaveChangesAsync(CancellationToken.None);

            // Notify the frontend via SignalR (non-fatal if the user is offline).
            try
            {
                await notificationService.SendChatResponseAsync(userIdStr, new()
                {
                    ConversationId    = conversationId,
                    AssistantMessageId = assistantMessageId,
                    Content           = assistantMsg.Content,
                }, CancellationToken.None);
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "ChatResponse SignalR push failed (non-fatal) for msg {MsgId}", assistantMessageId);
            }

            logger.LogInformation("ChatMessageProcessorJob completed for msg {MsgId}", assistantMessageId);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "ChatMessageProcessorJob failed for msg {MsgId}", assistantMessageId);

            try
            {
                assistantMsg.Fail("I encountered an error processing your message. Please try again.");
                await unitOfWork.SaveChangesAsync(CancellationToken.None);

                await notificationService.SendChatErrorAsync(userIdStr, new()
                {
                    ConversationId    = conversationId,
                    AssistantMessageId = assistantMessageId,
                    ErrorMessage      = assistantMsg.ErrorMessage!,
                }, CancellationToken.None);
            }
            catch (Exception innerEx)
            {
                logger.LogError(innerEx, "Failed to persist error state for msg {MsgId}", assistantMessageId);
            }
        }
    }
}
