/**
 * @file default-tours.ts
 * @description Pre-defined default guided tour scenarios for the Rafiq Assistant.
 * Scripts are clean Egyptian Arabic with تشكيل (Tashkeel) for correct TTS pronunciation.
 * Every step's highlighted anchor strictly matches the spoken speech text word-for-word.
 */

import { TourScenario } from '../models/tour-scenario';
import { DEFAULT_TOURS_EN } from './default-tours-en';

const ONBOARDING_FIXED_POSITION = { yFromBottom: 150 };

// ── Onboarding Tour — Guided profile creation ─────────────────────────────

export const ONBOARDING_TOUR: TourScenario = {
  id: 'onboarding-tour',
  title: 'إعداد الملف الصحي',
  description: 'جولة تعريفيّة أثناء إعداد الملف الصحي الأول',
  category: 'onboarding',
  steps: [
    {
      id: 'onboarding-welcome-step',
      route: '/onboarding/welcome',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: 'أَهْلًا بِكَ يا {{userName}} فِي رَفِيق. أَنَا مُساعِدُكَ الصِّحِّي الذَّكِي، وسَأُساعِدُكَ الآن فِي إِعْداد مَلَفِّكَ الصِّحِّي خُطْوَة بِخُطْوَة، وسَيَسْتَغْرِق ذَلِكَ أَقَلَّ مِن دَقِيقَتَين.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
      waitForUser: true,
    },
    {
      id: 'onboarding-step1-guide',
      route: '/onboarding/step1',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: 'فِي هَذِهِ الخُطْوَة، اُكْتُب بَياناتِكَ الشَّخْصِيَّة: تارِيخ المِيلاد والنَّوْع. هَذِهِ المَعْلُومات ضَرُورِيَّة لِإِعْداد مَلَفِّكَ الصِّحِّي.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      waitForUser: true,
    },
    {
      id: 'onboarding-step1b-guide',
      route: '/onboarding/step1b',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: 'الآن أَدْخِل مَعْلُوماتِكَ الجَسَدِيَّة: الطُّول، الوَزْن، وفَصِيلَة الدَّم. هَذِهِ المَعْلُومات تُساعِدُنِي عَلَى مُتابَعَة صِحَّتِكَ بِدِقَّة أَكْبَر.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      waitForUser: true,
    },
    {
      id: 'onboarding-emergency-guide',
      route: '/onboarding/emergency',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: 'أَضِف هُنا بَيانات شَخْص قَرِيب مِنْكَ لِلتَّواصُل مَعَه فِي حالات الطَّوارِئ. لَو تَأَخَّرْتَ فِي أَخْذ دَواءٍ مُهِمّ، سَأُرْسِل لَه رِسالَة تَنْبِيه عَلَى الوَاتْساب فَوْرًا.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      waitForUser: true,
    },
    {
      id: 'onboarding-step2-guide',
      route: '/onboarding/step2',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: 'هَل لَدَيْكَ حَساسِيَّة مِن أَي طَعام أَو دَواء؟ إِن كانَ الأَمْر كَذَلِك، سَجِّلْها هُنا حَتَّى أُنَبِّهَكَ دائِمًا قَبْل وَصْف أَي عِلاج جَدِيد.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      waitForUser: true,
    },
    {
      id: 'onboarding-step3-guide',
      route: '/onboarding/step3',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: 'إِن كُنْتَ تُعانِي مِن أَي مَرَض مُزْمِن، سَجِّلْه هُنا لِأَتَمَكَّن مِن مُتابَعَة حالَتِكَ وتَقْدِيم النَّصائِح المُناسِبَة لَك.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      waitForUser: true,
    },
    {
      id: 'onboarding-step4-guide',
      route: '/onboarding/step4',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: 'مُمْتاز! هَذِهِ مُراجَعَة شامِلَة لِكُل البَيانات الَّتِي أَدْخَلْتَها. تَأَكَّد مِنْها، وبَعْدَها سَنَنْتَقِل مَعًا إِلَى لَوْحَة التَّحَكُّم.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      waitForUser: true,
    },
  ],
};

// ── Welcome Tour — Comprehensive Application & Dashboard Walkthrough ───────

export const WELCOME_TOUR: TourScenario = {
  id: 'welcome-tour',
  title: 'الجولة التعريفية الشاملة الكبرى للتطبيق',
  description: 'جولة شاملة ومفصلة تجمع كافة خطوات الجولات التخصصية وتتنقل عبر جميع صفحات وأقسام تطبيق رفيق',
  category: 'onboarding',
  steps: [
    // ── Welcome Intro ──
    {
      id: 'welcome-greeting',
      route: '/dashboard',
      speech: 'أَهْلًا بِكَ يا {{userName}} فِي رَفِيق! سَآخُذُكَ الآن فِي جَوْلَةٍ شامِلَةٍ عَبْرَ كُلِّ صَفَحاتِ وأَقْسامِ وتَفاصِيلِ التَّطْبِيقِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },

    // ── Part 1: Dashboard Details ──
    {
      id: 'dash-ai-summary',
      anchor: 'ai-health-summary-card',
      route: '/dashboard',
      speech: 'فِي لَوْحَةِ التَّحَكُّم، هُنا \'المُلَخَّص الصِّحِّي الذَّكِي\' يَعْرِض حَسَبَ بَياناتِكَ الطِّبِّيَّة التَّوصِيات والتَّقْيِيم الصِّحِّي.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-ai-details-btn',
      anchor: 'ai-summary-details-btn',
      route: '/dashboard',
      speech: 'واِضْغَطْ عَلَى زِرِّ \'اسأل الذكاء الاصطناعي للتفاصيل\' لِمُناقَشَةِ أَيِّ جُزْئِيَّةٍ فِي المُلَخَّصِ مَعِي.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-today-schedule',
      anchor: 'today-schedule-section',
      route: '/dashboard',
      speech: 'وهُنا قِسْم \'اليَوْم\' لِمُتابَعَة المَواعِيد المُنْتَظَرَة وجُرَعات الأَدْوِيَة وهَدَف المَاء.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'dash-qa-upload',
      anchor: 'qa-upload-record',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'رَفْع سِجِلّ\' لِرَفْع الرُّوشِتَّات والتَّحالِيل والأَشِعَّة لِيَقُوم الذَّكاء الاصْطِناعِي بِفَحْصِها المَبْدَئِي فَوْرًا.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-appointments',
      anchor: 'qa-appointments',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'المَواعِيد\' لِحَجْز زِياراتِكَ الطِّبِّيَّة وتَنْظِيم مَواعِيد الأَطِبّاءِ وتَنْبِيهات المَواعِيد.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-reminders',
      anchor: 'qa-reminders',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'التَّذْكِيرات\' لِإِدارَة وتَسْجِيل أَدْوِيَتِكَ، وتَحْدِيد مَواعِيد الجُرَعات اليَوْمِيَّة.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-aichat',
      anchor: 'ai-chat-quick-action',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'مَحادَثَة الذَّكاء الاصْطِناعِي\' لِلتَّحَدُّث مَعِي صَوْتِيًّا أَو كِتابِيًّا فِي أَي وَقْت لِلإِجابَةِ عَن أَي اسْتِفْسار طِبِّي.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-qa-family',
      anchor: 'qa-family',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'العائِلَة\' لِمُتابَعَة وإِدارَة مَلَفَّات صِحَّة وأَدْوِيَة كُل أُسْرَتِكَ فِي مَكان واحِد.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-upcoming-appt',
      route: '/dashboard',
      variants: {
        populated: {
          anchor: 'upcoming-appointment-detail',
          speech: 'وهُنا بِطاقَة \'المَواعِيد القادِمَة\' تَعْرِض تَفاصِيل مَوْعِدِكَ القادِم مَع الطَّبِيب.',
        },
        empty: {
          anchor: 'add-appointment-button',
          speech: 'وهُنا بِطاقَة \'المَواعِيد القادِمَة\'. عِنْدَ إِضافَة مَوْعِد، سَيَظْهَر هُنا، واِضْغَط إِضافَة لِحَجْزِ مَوْعِد.',
        },
      },
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-meds',
      anchor: 'medications-reminders-card',
      route: '/dashboard',
      speech: 'وهُنا \'الأَدْوِيَة والتَّذْكِيرات\' لِمُتابَعَة الجُرَعات وتَسْجِيل تَناوُلِ الدَّواء.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-family',
      anchor: 'family-overview-section',
      route: '/dashboard',
      speech: 'وهُنا \'نَظْرَة عائِلِيَّة\' لِمُتابَعَة حالَة صِحَّة أَفْراد عائِلَتِكَ.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-records',
      anchor: 'recent-records-card',
      route: '/dashboard',
      speech: 'وهُنا آخِر السِّجِلَّات الطِّبِّيَّة والتَّحالِيل المَرْفُوعَة مؤَخَّرًا.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },

    // ── Part 2: Medical Records Page ──
    {
      id: 'mr-welcome',
      route: '/medical-records',
      speech: 'والآن نَنْتَقِلُ لِصَفْحَة \'السِّجِلَّات الطِّبِّيَّة\'. سَأُنَظِّمُ لَكَ كُلَّ مَلَفَّاتِكَ ومُسْتَنَداتِكَ الطِّبِّيَّةِ هُنا.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'mr-search',
      anchor: 'mr-search-bar',
      route: '/medical-records',
      speech: 'هُنا شَرِيطُ البَحْثِ والتَّصْفِيَةِ. يُمْكِنُكَ البَحْثُ عَنْ أَيِّ رُوشِتَّةٍ أَوْ تَحْلِيلٍ بِالاسْمِ أَوْ اسْمِ الطَّبِيبِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-general',
      anchor: 'mr-card-general',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'تقارير طبية\'. يَعْرِضُ كُلَّ المُلَخَّصاتِ والمُسْتَنَداتِ الطِّبِّيَّةِ العامَّةِ المَرْفُوعَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-medicine',
      anchor: 'mr-card-medicine',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'أدوية\'. يَعْرِضُ كُلَّ عُبُواتِ الأَدْوِيَةِ وتَفاصِيلِ الجُرَعاتِ المَسَحُوحَةِ لَدَيْكَ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-prescription',
      anchor: 'mr-card-prescription',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'الروشتات\'. يَعْرِضُ كُلَّ الرُّوشِتَّاتِ الطِّبِّيَّةِ الصّادِرَةِ مِن الأَطِبّاءِ مَعَ اسْتِخْراجِ الأَدْوِيَةِ ذَكِيًّا.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-imaging',
      anchor: 'mr-card-imaging',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'الأشعة\'. يَعْرِضُ صُوَرَ التَّصْوِيرِ الطِّبِّي كَالأَشِعَّةِ السِّينِيَّةِ والرَّنِينِ المَغْناطِيسِي والسُّونار.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-lab',
      anchor: 'mr-card-lab',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'التحاليل\'. يَعْرِضُ كُلَّ نَتائِجِ تَحالِيلِ الدَّمِ والمَعابِرِ الطِّبِّيَّةِ مَعَ تَحْلِيلِ الذَّكاءِ الاصْطِناعِي.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-recent',
      anchor: 'mr-recent-list',
      route: '/medical-records',
      speech: 'وهُنا قائِمَة \'آخر السجلات\'. اِضْغَط عَلَى أَيِّ سِجِلٍّ لِعَرْضِ التَّفاصِيلِ أَوْ التَّعْدِيلِ أَوْ الحَذْفِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-add',
      anchor: 'add-record-button',
      route: '/medical-records',
      speech: 'واِضْغَطْ عَلَى \'إضافة سجل جديد\' فِي أَيِّ وَقْتٍ لِرَفْعِ مُسْتَنَدٍ جَدِيدٍ عَبْرَ المَسْحِ الضَّوْئِي، الكامِيرا، أَو المَلَفّاتِ!',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 3: Appointments Page ──
    {
      id: 'appt-welcome',
      route: '/appointments',
      speech: 'ونَنْتَقِلُ الآن لِصَفْحَة \'المَواعِيد الطِّبِّيَّة\'. سَأُساعِدُكَ فِي تَنْظِيم وتَتَبُّع كُلِّ زِياراتِكَ لِلأَطِبّاءِ وتَنْبِيهات المَواعِيد.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'appt-upcoming',
      anchor: 'appts-upcoming-card',
      route: '/appointments',
      speech: 'هُنا بِطاقَة \'المَوْعِد القادِم\'. تَعْرِضُ اسْمَ الطَّبِيب، التَّخَصُّصَ، ومَوْعِدَ الزِّيارَةِ المُنْتَظَرَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-chips',
      anchor: 'appts-summary-chips',
      route: '/appointments',
      speech: 'وهُنا \'نَظْرَة سَرِيعَة\' لِمُتابَعَةِ عَدَدِ المَواعِيدِ المُنْتَظَرَةِ، المُكْتَمِلَةِ، والمُلْغاةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-list',
      anchor: 'appts-upcoming-list',
      route: '/appointments',
      speech: 'وهُنا \'قائِمَة المَواعِيد القادِمَة\'. تَعْرِضُ المَواعِيدَ المُنْتَظَرَةِ بِالتَّرْتِيبِ الزَّمَنِيِّ مَعَ إِمْكانِيَّةِ عَرْضِ التَّفاصِيلِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-history',
      anchor: 'appts-history-section',
      route: '/appointments',
      speech: 'وهُنا \'سِجِلّ المَواعِيد السّابِقَة\'. يُمَكِّنُكَ مِن مُراجَعَةِ الزِّياراتِ الطِّبِّيَّةِ القَدِيمَةِ والتَّصْفِيَةِ حَسَبَ الشَّهْرِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-settings',
      anchor: 'appts-reminder-settings',
      route: '/appointments',
      speech: 'وهُنا \'إِعْدادات التَّذْكِير\'. تُمَكِّنُكَ مِن تَشْغِيلِ التَّنْبِيهاتِ وتَحْدِيدِ تَوْقِيتِ التَّذْكِيرِ قَبْل 15 دَقِيقَة أَوْ ساعَة أَوْ يَوم.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'appt-add',
      anchor: 'add-appointment',
      route: '/appointments',
      speech: 'واِضْغَطْ عَلَى زِرِّ \'+\' الدّائِرِيِّ العائِمِ فِي الأسْفَلِ فِي أَيِّ وَقْتٍ لِحَجْزِ زِيارَةٍ طِبِّيَّةٍ جَدِيدَةٍ!',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 4: Medications & Reminders Page ──
    {
      id: 'med-welcome',
      route: '/medications',
      speech: 'ونَنْتَقِلُ الآن لِصَفْحَة \'الأَدْوِيَةِ والتَّذْكِيرات\'. سَأُساعِدُكَ فِي ضَبْطِ جُرَعاتِكَ وتَنْبِيهاتِ الأَدْوِيَةِ فِي مَواعِيدِها.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'med-add-btn',
      anchor: 'add-medication-btn',
      route: '/medications',
      speech: 'اِضْغَطْ عَلَى زِرِّ \'إضافة دواء\' فِي أَيِّ وَقْتٍ لِإِضافَةِ دَواءٍ جَدِيدٍ وتَحْدِيدِ أَوْقاتِ التَّنْبِيهاتِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'med-today',
      anchor: 'med-today-glance',
      route: '/medications',
      speech: 'وهُنا \'نَظْرَة عامَّة اليَوْم\'. تَعْرِضُ لَكَ عَدَدَ جُرَعاتِ اليَوْم المَأْخُوذَةِ والمَتَبَقِّيَةِ والمتأَخِّرَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'med-active-list',
      anchor: 'med-active-list',
      route: '/medications',
      speech: 'وهُنا قائِمَة \'أَدْوِيَتِكَ النَّشِطَة\'. تَعْرِضُ كُلَّ عُبُواتِ الأَدْوِيَةِ مَعَ جُرَعاتِها وأَوْقاتِ التَّنْبِيهاتِ المَضْبُوطَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 5: My Profile Page ──
    {
      id: 'profile-welcome',
      route: '/my-profile',
      speech: 'والآن نَنْتَقِلُ لِصَفْحَتِكَ الشَّخْصِيَّة. سَأُساعِدُكَ فِي إِدارَةِ بَياناتِكَ الشَّخْصِيَّةِ والصِّحِّيَّةِ وإِعْداداتِ الحِساب.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'profile-hero',
      anchor: 'profile-hero-card',
      route: '/my-profile',
      speech: 'فِي الأَعْلَى، هُنا بِطاقَتُكَ الرَّئِيسِيَّة الَّتِي تَعْرِضُ صُورَتَكَ الشَّخْصِيَّة، اسْمَكَ، وإِحْصائِيّاتِ عُضْوِيَّتِكَ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-personal-btn',
      anchor: 'profile-personal-info',
      route: '/my-profile',
      speech: 'اِضْغَطْ عَلَى \'البيانات الشخصية\' لِتَعْدِيل اسْمِكَ، تارِيخ المِيلاد، رَقْم الهاتِف، والنَّوْع.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-health-btn',
      anchor: 'profile-health-info',
      route: '/my-profile',
      speech: 'واِضْغَطْ عَلَى \'المعلومات الصحية\' لِإِدارَةِ فَصِيلَة الدَّم، الطُّول، الوَزْن، الحَساسِيَّة، والأَمْراضِ المُزْمِنَة.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-emergency-btn',
      anchor: 'profile-emergency-contacts',
      route: '/my-profile',
      speech: 'وهُنا \'جهات الطوارئ\'. سَجِّلْ أَرْقامَ التَّواصُل الطّارِئ لِلإِشْعارِ الفَوْرِيِّ فِي حالاتِ الطَّوارِئ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-family-btn',
      anchor: 'profile-family-profiles',
      route: '/my-profile',
      speech: 'وهُنا \'ملفات العائلة\'. يُمْكِنُكَ إِضافَةُ بَياناتِ أَفْرادِ عائِلَتِكَ ومُتابَعَةُ المَلَفّاتِ الصِّحِّيَّةِ لَهُمْ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-settings-btn',
      anchor: 'profile-settings',
      route: '/my-profile',
      speech: 'وهُنا \'الإعدادات\'. اضْغَطْ هُنا لِتَغْيِيرِ اللُّغَة، إِدارَة التَّنْبِيهاتِ، وتَحْدِيثِ كَلِمَة المُرُور.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-rate-btn',
      anchor: 'profile-rate-rafiq',
      route: '/my-profile',
      speech: 'ولا تَنْسَ خِتامًا تَقْيِيمَ رَفِيقٍ باِضْغاطِك عَلَى \'تقييم رفيق\' ومَنَحِنا 5 نُجُومٍ لِنَسْتَمِرَّ فِي تَقْدِيمِ الأَفْضَلِ لَك!',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 6: Return to Dashboard & Spotlight Tour Button ──
    {
      id: 'welcome-finish',
      anchor: 'header-tour-btn',
      route: '/dashboard',
      speech: 'بِهَذا نَكُونُ قَدْ زُرْنا ورَأَيْنا كُلَّ زِرٍّ وقِسْمٍ فِي كُلِّ صَفَحاتِ التَّطْبِيقِ! فِي أَيِّ صَفْحَةٍ، اِضْغَطْ عَلَى زِرِّ الجَوْلَة (?) فِي الأَعْلَى لِبَدْءِ الجَوْلَةِ المِفَصَّلَةِ الخاصَّةِ بِها!',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
  onStart: () => console.log('[WelcomeTour] started'),
  onComplete: () => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('rafiq_tour_completed', 'true');
    }
  },
  onCancel: () => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('rafiq_tour_completed', 'true');
    }
  },
};

// ── Dashboard Tour ──────────────────────────────────────────────────────────

export const DASHBOARD_TOUR: TourScenario = {
  id: 'dashboard-tour',
  title: 'جولة لوحة التحكم المفصلة',
  description: 'تعرف تفصيلياً على كل قسم وزر في لوحة التحكم الصحية',
  category: 'onboarding',
  steps: [
    {
      id: 'dash-welcome',
      route: '/dashboard',
      speech: 'أَهْلًا بِكَ يا {{userName}} فِي لَوْحَة التَّحَكُّم. سَأَشْرَحُ لَكَ كُل زِرّ وقِسْم بِالتَّفْصِيل.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'dash-ai-summary',
      anchor: 'ai-health-summary-card',
      route: '/dashboard',
      speech: 'هُنا \'المُلَخَّص الصِّحِّي الذَّكِي\' يَعْرِض حَسَبَ بَياناتِكَ الطِّبِّيَّة التَّوصِيات والتَّقْيِيم الصِّحِّي.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-ai-details-btn',
      anchor: 'ai-summary-details-btn',
      route: '/dashboard',
      speech: 'واِضْغَطْ عَلَى زِرِّ \'اسأل الذكاء الاصطناعي للتفاصيل\' لِمُناقَشَةِ أَيِّ جُزْئِيَّةٍ فِي المُلَخَّصِ مَعِي.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-today-schedule',
      anchor: 'today-schedule-section',
      route: '/dashboard',
      speech: 'وهُنا قِسْم \'اليَوْم\' لِمُتابَعَة المَواعِيد المُنْتَظَرَة وجُرَعات الأَدْوِيَة وهَدَف المَاء.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'dash-qa-upload',
      anchor: 'qa-upload-record',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'رَفْع سِجِلّ\' لِرَفْع الرُّوشِتَّات والتَّحالِيل والأَشِعَّة لِيَقُوم الذَّكاء الاصْطِناعِي بِفَحْصِها المَبْدَئِي فَوْرًا.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-appointments',
      anchor: 'qa-appointments',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'المَواعِيد\' لِحَجْز زِياراتِكَ الطِّبِّيَّة وتَنْظِيم مَواعِيد الأَطِبّاءِ وتَنْبِيهات المَواعِيد.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-reminders',
      anchor: 'qa-reminders',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'التَّذْكِيرات\' لِإِدارَة وتَسْجِيل أَدْوِيَتِكَ، وتَحْدِيد مَواعِيد الجُرَعات اليَوْمِيَّة.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-aichat',
      anchor: 'ai-chat-quick-action',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'مَحادَثَة الذَّكاء الاصْطِناعِي\' لِلتَّحَدُّث مَعِي صَوْتِيًّا أَو كِتابِيًّا فِي أَي وَقْت لِلإِجابَةِ عَن أَي اسْتِفْسار طِبِّي.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-qa-family',
      anchor: 'qa-family',
      route: '/dashboard',
      speech: 'وهُنا زِرّ \'العائِلَة\' لِمُتابَعَة وإِدارَة مَلَفَّات صِحَّة وأَدْوِيَة كُل أُسْرَتِكَ فِي مَكان واحِد.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-upcoming-appt',
      route: '/dashboard',
      variants: {
        populated: {
          anchor: 'upcoming-appointment-detail',
          speech: 'وهُنا بِطاقَة \'المَواعِيد القادِمَة\' تَعْرِض تَفاصِيل مَوْعِدِكَ القادِم مَع الطَّبِيب.',
        },
        empty: {
          anchor: 'add-appointment-button',
          speech: 'وهُنا بِطاقَة \'المَواعِيد القادِمَة\'. عِنْدَ إِضافَة مَوْعِد، سَيَظْهَر هُنا، واِضْغَط إِضافَة لِحَجْزِ مَوْعِد.',
        },
      },
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-meds',
      anchor: 'medications-reminders-card',
      route: '/dashboard',
      speech: 'وهُنا \'الأَدْوِيَة والتَّذْكِيرات\' لِمُتابَعَة الجُرَعات وتَسْجِيل تَناوُلِ الدَّواء.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-family',
      anchor: 'family-overview-section',
      route: '/dashboard',
      speech: 'وهُنا \'نَظْرَة عائِلِيَّة\' لِمُتابَعَة حالَة صِحَّة أَفْراد عائِلَتِكَ.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-records',
      anchor: 'recent-records-card',
      route: '/dashboard',
      speech: 'وهُنا آخِر السِّجِلَّات الطِّبِّيَّة والتَّحالِيل المَرْفُوعَة مؤَخَّرًا.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
  ],
};

// ── Medical Records Tour ────────────────────────────────────────────────────

export const MEDICAL_RECORDS_TOUR: TourScenario = {
  id: 'medical-records-tour',
  title: 'جولة السجلات الطبية المفصلة',
  description: 'تعرف تفصيلياً على كل قسم وفئة وسجل في صفحة السجلات الطبية',
  category: 'onboarding',
  steps: [
    {
      id: 'mr-welcome',
      route: '/medical-records',
      speech: 'مَرْحَبًا بِكَ فِي صَفْحَة \'السِّجِلَّات الطِّبِّيَّة\'. سَأُنَظِّمُ لَكَ كُلَّ مَلَفَّاتِكَ ومُسْتَنَداتِكَ الطِّبِّيَّةِ هُنا.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'mr-search',
      anchor: 'mr-search-bar',
      route: '/medical-records',
      speech: 'هُنا شَرِيطُ البَحْثِ والتَّصْفِيَةِ. يُمْكِنُكَ البَحْثُ عَنْ أَيِّ رُوشِتَّةٍ أَوْ تَحْلِيلٍ بِالاسْمِ أَوْ اسْمِ الطَّبِيبِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-general',
      anchor: 'mr-card-general',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'التقارير الطبية\'. يَعْرِضُ كُلَّ المُلَخَّصاتِ والمُسْتَنَداتِ الطِّبِّيَّةِ العامَّةِ المَرْفُوعَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-medicine',
      anchor: 'mr-card-medicine',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'الأدوية\'. يَعْرِضُ كُلَّ عُبُواتِ الأَدْوِيَةِ وتَفاصِيلِ الجُرَعاتِ المَسَحُوحَةِ لَدَيْكَ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-prescription',
      anchor: 'mr-card-prescription',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'الروشتات\'. يَعْرِضُ كُلَّ الرُّوشِتَّاتِ الطِّبِّيَّةِ الصّادِرَةِ مِن الأَطِبّاءِ مَعَ اسْتِخْراجِ الأَدْوِيَةِ ذَكِيًّا.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-imaging',
      anchor: 'mr-card-imaging',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'الأشعة\'. يَعْرِضُ صُوَرَ التَّصْوِيرِ الطِّبِّي كَالأَشِعَّةِ السِّينِيَّةِ والرَّنِينِ المَغْناطِيسِي والسُّونار.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-lab',
      anchor: 'mr-card-lab',
      route: '/medical-records',
      speech: 'وهُنا قِسْم \'التحاليل\'. يَعْرِضُ كُلَّ نَتائِجِ تَحالِيلِ الدَّمِ والمَعابِرِ الطِّبِّيَّةِ مَعَ تَحْلِيلِ الذَّكاءِ الاصْطِناعِي.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-recent',
      anchor: 'mr-recent-list',
      route: '/medical-records',
      speech: 'وهُنا قائِمَة \'آخر السجلات\'. اِضْغَط عَلَى أَيِّ سِجِلٍّ لِعَرْضِ التَّفاصِيلِ أَوْ التَّعْدِيلِ أَوْ الحَذْفِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-add',
      anchor: 'add-record-button',
      route: '/medical-records',
      speech: 'واِضْغَطْ عَلَى \'إضافة سجل جديد\' فِي أَيِّ وَقْتٍ لِرَفْعِ مُسْتَنَدٍ جَدِيدٍ عَبْرَ المَسْحِ الضَّوْئِي، الكامِيرا، أَو المَلَفّاتِ!',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── Appointments Tour ───────────────────────────────────────────────────────

export const APPOINTMENTS_TOUR: TourScenario = {
  id: 'appointments-tour',
  title: 'جولة المواعيد الطبية المفصلة',
  description: 'تعرف تفصيلياً على كل بطاقة وسجل وإعداد في صفحة المواعيد الطبية',
  category: 'onboarding',
  steps: [
    {
      id: 'appt-welcome',
      route: '/appointments',
      speech: 'مَرْحَبًا بِكَ فِي صَفْحَة \'المَواعِيد الطِّبِّيَّة\'. سَأُساعِدُكَ فِي تَنْظِيم وتَتَبُّع كُلِّ زِياراتِكَ لِلأَطِبّاءِ وتَنْبِيهات المَواعِيد.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'appt-upcoming',
      anchor: 'appts-upcoming-card',
      route: '/appointments',
      speech: 'هُنا بِطاقَة \'المَوْعِد القادِم\'. تَعْرِضُ اسْمَ الطَّبِيب، التَّخَصُّصَ، ومَوْعِدَ الزِّيارَةِ المُنْتَظَرَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-chips',
      anchor: 'appts-summary-chips',
      route: '/appointments',
      speech: 'وهُنا \'نَظْرَة سَرِيعَة\' لِمُتابَعَةِ عَدَدِ المَواعِيدِ المُنْتَظَرَةِ، المُكْتَمِلَةِ، والمُلْغاةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-list',
      anchor: 'appts-upcoming-list',
      route: '/appointments',
      speech: 'وهُنا \'قائِمَة المَواعِيد القادِمَة\'. تَعْرِضُ المَواعِيدَ المُنْتَظَرَةِ بِالتَّرْتِيبِ الزَّمَنِيِّ مَعَ إِمْكانِيَّةِ عَرْضِ التَّفاصِيلِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-history',
      anchor: 'appts-history-section',
      route: '/appointments',
      speech: 'وهُنا \'سِجِلّ المَواعِيد السّابِقَة\'. يُمَكِّنُكَ مِن مُراجَعَةِ الزِّياراتِ الطِّبِّيَّةِ القَدِيمَةِ والتَّصْفِيَةِ حَسَبَ الشَّهْرِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-settings',
      anchor: 'appts-reminder-settings',
      route: '/appointments',
      speech: 'وهُنا \'إِعْدادات التَّذْكِير\'. تُمَكِّنُكَ مِن تَشْغِيلِ التَّنْبِيهاتِ وتَحْدِيدِ تَوْقِيتِ التَّذْكِيرِ قَبْل 15 دَقِيقَة أَوْ ساعَة أَوْ يَوم.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'appt-add',
      anchor: 'add-appointment',
      route: '/appointments',
      speech: 'واِضْغَطْ عَلَى زِرِّ \'+\' الدّائِرِيِّ العائِمِ فِي الأسْفَلِ فِي أَيِّ وَقْتٍ لِحَجْزِ زِيارَةٍ طِبِّيَّةٍ جَدِيدَةٍ!',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── Medications Tour ────────────────────────────────────────────────────────

export const MEDICATIONS_TOUR: TourScenario = {
  id: 'medications-tour',
  title: 'جولة الأدوية والتذكيرات المفصلة',
  description: 'تعرف تفصيلياً على إدارة الأدوية والجرعات والتنبيهات',
  category: 'onboarding',
  steps: [
    {
      id: 'med-welcome',
      route: '/medications',
      speech: 'مَرْحَبًا بِكَ فِي صَفْحَة \'الأَدْوِيَةِ والتَّذْكِيرات\'. سَأُساعِدُكَ فِي ضَبْطِ جُرَعاتِكَ وتَنْبِيهاتِ الأَدْوِيَةِ فِي مَواعِيدِها.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'med-add-btn',
      anchor: 'add-medication-btn',
      route: '/medications',
      speech: 'اِضْغَطْ عَلَى زِرِّ \'إضافة دواء\' فِي أَيِّ وَقْتٍ لِإِضافَةِ دَواءٍ جَدِيدٍ وتَحْدِيدِ أَوْقاتِ التَّنْبِيهاتِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'med-today',
      anchor: 'med-today-glance',
      route: '/medications',
      speech: 'وهُنا \'نَظْرَة عامَّة اليَوْم\'. تَعْرِضُ لَكَ عَدَدَ جُرَعاتِ اليَوْم المَأْخُوذَةِ والمَتَبَقِّيَةِ والمتأَخِّرَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'med-active-list',
      anchor: 'med-active-list',
      route: '/medications',
      speech: 'وهُنا قائِمَة \'أَدْوِيَتِكَ النَّشِطَة\'. تَعْرِضُ كُلَّ عُبُواتِ الأَدْوِيَةِ مَعَ جُرَعاتِها وأَوْقاتِ التَّنْبِيهاتِ المَضْبُوطَةِ.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── Family Profiles Tour ────────────────────────────────────────────────────

export const FAMILY_PROFILES_TOUR: TourScenario = {
  id: 'family-profiles-tour',
  title: 'جولة ملفات العائلة',
  description: 'تعرف على إدارة ملفات أفراد العائلة',
  category: 'onboarding',
  steps: [
    {
      id: 'family-list',
      anchor: 'family-profiles-list',
      route: '/family-profiles',
      speech: 'فِي صَفْحَة العائِلَة، هُنا يُمْكِنُكَ اسْتِعْراض والتَّنَقُّل بَيْن مَلَفَّات أَفْراد أُسْرَتِكَ.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'family-add-btn',
      anchor: 'add-family-profile',
      route: '/family-profiles',
      speech: 'واِضْغَط عَلَى \'إِضافَة فَرْد عائِلَة\' لِإِضافَة مَلَفّ جَدِيد ومُتابَعَة صِحَّتِهِ مَعَك.',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── My Profile Tour ─────────────────────────────────────────────────────────

export const MY_PROFILE_TOUR: TourScenario = {
  id: 'my-profile-tour',
  title: 'جولة الملف الشخصي المفصلة',
  description: 'تعرف تفصيلياً على إدارة البيانات الشخصية والصحية وإعدادات الحساب',
  category: 'onboarding',
  steps: [
    {
      id: 'profile-welcome',
      route: '/my-profile',
      speech: 'مَرْحَبًا بِكَ فِي صَفْحَتِكَ الشَّخْصِيَّة. سَأُساعِدُكَ فِي إِدارَةِ بَياناتِكَ الشَّخْصِيَّةِ والصِّحِّيَّةِ وإِعْداداتِ الحِساب.',
      speechLanguage: 'ar-EG',
      avatarState: 'wave',
    },
    {
      id: 'profile-hero',
      anchor: 'profile-hero-card',
      route: '/my-profile',
      speech: 'فِي الأَعْلَى، هُنا بِطاقَتُكَ الرَّئِيسِيَّة الَّتِي تَعْرِضُ صُورَتَكَ الشَّخْصِيَّة، اسْمَكَ، وإِحْصائِيّاتِ عُضْوِيَّتِكَ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-personal-btn',
      anchor: 'profile-personal-info',
      route: '/my-profile',
      speech: 'اِضْغَطْ عَلَى \'البيانات الشخصية\' لِتَعْدِيل اسْمِكَ، تارِيخ المِيلاد، رَقْم الهاتِف، والنَّوْع.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-health-btn',
      anchor: 'profile-health-info',
      route: '/my-profile',
      speech: 'واِضْغَطْ عَلَى \'المعلومات الصحية\' لِإِدارَةِ فَصِيلَة الدَّم، الطُّول، الوَزْن، الحَساسِيَّة، والأَمْراضِ المُزْمِنَة.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-emergency-btn',
      anchor: 'profile-emergency-contacts',
      route: '/my-profile',
      speech: 'وهُنا \'جهات الطوارئ\'. سَجِّلْ أَرْقامَ التَّواصُل الطّارِئ لِلإِشْعارِ الفَوْرِيِّ فِي حالاتِ الطَّوارِئ.',
      speechLanguage: 'ar-EG',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-family-btn',
      anchor: 'profile-family-profiles',
      route: '/my-profile',
      speech: 'وهُنا \'ملفات العائلة\'. يُمْكِنُكَ إِضافَةُ بَياناتِ أَفْرادِ عائِلَتِكَ ومُتابَعَةُ المَلَفّاتِ الصِّحِّيَّةِ لَهُمْ.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-settings-btn',
      anchor: 'profile-settings',
      route: '/my-profile',
      speech: 'وهُنا \'الإعدادات\'. اضْغَطْ هُنا لِتَغْيِيرِ اللُّغَة، إِدارَة التَّنْبِيهاتِ، وتَحْدِيثِ كَلِمَة المُرُور.',
      speechLanguage: 'ar-EG',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-rate-btn',
      anchor: 'profile-rate-rafiq',
      route: '/my-profile',
      speech: 'ولا تَنْسَ خِتامًا تَقْيِيمَ رَفِيقٍ باِضْغاطِك عَلَى \'تقييم رفيق\' ومَنَحِنا 5 نُجُومٍ لِنَسْتَمِرَّ فِي تَقْدِيمِ الأَفْضَلِ لَك!',
      speechLanguage: 'ar-EG',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

export const DEFAULT_TOURS: TourScenario[] = [
  ONBOARDING_TOUR,
  WELCOME_TOUR,
  DASHBOARD_TOUR,
  MEDICAL_RECORDS_TOUR,
  APPOINTMENTS_TOUR,
  MEDICATIONS_TOUR,
  FAMILY_PROFILES_TOUR,
  MY_PROFILE_TOUR,
  ...DEFAULT_TOURS_EN,
];
