/**
 * @file default-tours-en.ts
 * @description English versions of all guided tour scenarios.
 * Each scenario ID mirrors the Arabic version with an "-en" suffix so the
 * tour engine can auto-select the right language at runtime.
 * Every step's highlighted anchor strictly matches the spoken speech text word-for-word.
 */

import { TourScenario } from '../models/tour-scenario';

const ONBOARDING_FIXED_POSITION = { yFromBottom: 150 };

// ── Onboarding Tour (English) ──────────────────────────────────────────────

export const ONBOARDING_TOUR_EN: TourScenario = {
  id: 'onboarding-tour-en',
  title: 'Setting Up Your Health Profile',
  description: 'Guided tour during first-time health profile setup',
  category: 'onboarding',
  steps: [
    {
      id: 'onboarding-welcome-step-en',
      route: '/onboarding/welcome',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: "Welcome to Rafiq, {{userName}}! I'm your AI health companion. I'll guide you through setting up your health profile step by step — it will take less than two minutes.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
      waitForUser: true,
    },
    {
      id: 'onboarding-step1-guide-en',
      route: '/onboarding/step1',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: "Enter your personal details here: your date of birth and gender. This is the foundation of your health profile.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      waitForUser: true,
    },
    {
      id: 'onboarding-step1b-guide-en',
      route: '/onboarding/step1b',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: "Now enter your physical measurements: height, weight, and blood type. These help me monitor your health with greater precision.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      waitForUser: true,
    },
    {
      id: 'onboarding-emergency-guide-en',
      route: '/onboarding/emergency',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: "Add an emergency contact here — someone close to you I can reach in urgent situations. If you're late taking an important medication, I'll send them an instant WhatsApp alert.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      waitForUser: true,
    },
    {
      id: 'onboarding-step2-guide-en',
      route: '/onboarding/step2',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: "Do you have any allergies to food or medication? If so, record them here so I can always alert you before any new treatment is prescribed.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      waitForUser: true,
    },
    {
      id: 'onboarding-step3-guide-en',
      route: '/onboarding/step3',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: "If you have any chronic conditions, record them here so I can follow your case and give you tailored advice.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      waitForUser: true,
    },
    {
      id: 'onboarding-step4-guide-en',
      route: '/onboarding/step4',
      fixedPositionFromBottom: ONBOARDING_FIXED_POSITION,
      speech: "Excellent! This is a complete review of all the information you entered. Verify everything looks right, and then we'll head to the dashboard together.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      waitForUser: true,
    },
  ],
};

// ── Welcome Tour (English) ─────────────────────────────────────────────────

export const WELCOME_TOUR_EN: TourScenario = {
  id: 'welcome-tour-en',
  title: 'Grand Master Application Tour',
  description: 'A comprehensive master tour combining all specific page tour steps into one seamless journey across all sections of Rafiq',
  category: 'onboarding',
  steps: [
    // ── Welcome Intro ──
    {
      id: 'welcome-greeting-en',
      route: '/dashboard',
      speech: "Welcome {{userName}} to Rafiq! Let me take you on a grand master tour covering every page, feature, and section of your application.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },

    // ── Part 1: Dashboard Details ──
    {
      id: 'dash-ai-summary-en',
      anchor: 'ai-health-summary-card',
      route: '/dashboard',
      speech: "Here is your AI Health Summary, continuously analyzing your medical data to deliver personalized health recommendations.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-ai-details-btn-en',
      anchor: 'ai-summary-details-btn',
      route: '/dashboard',
      speech: "And tap 'Ask AI for details' to ask me to explain any specific item in your health summary in full detail!",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-today-schedule-en',
      anchor: 'today-schedule-section',
      route: '/dashboard',
      speech: "This is the 'Today' section, displaying your upcoming appointments, scheduled medication doses, and water intake tracker.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'dash-qa-upload-en',
      anchor: 'qa-upload-record',
      route: '/dashboard',
      speech: "Here is 'Upload Record' in Quick Actions. Tap it to upload lab test results, prescriptions, or scans so AI can analyze them instantly!",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-appointments-en',
      anchor: 'qa-appointments',
      route: '/dashboard',
      speech: "Here is 'Appointments'. Tap it to schedule doctor visits, manage appointment dates, and set reminder lead times!",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-reminders-en',
      anchor: 'qa-reminders',
      route: '/dashboard',
      speech: "Here is 'Reminders'. Tap it to manage your pill schedules, set dose timings, and track your daily medications!",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-aichat-en',
      anchor: 'ai-chat-quick-action',
      route: '/dashboard',
      speech: "Here is 'AI Chat'. Tap it anytime to talk with me via voice commands or text chat to get immediate answers to your medical questions!",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-qa-family-en',
      anchor: 'qa-family',
      route: '/dashboard',
      speech: "And here is 'Family'. Tap it to manage health profiles, appointments, and medications for all your family members!",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-upcoming-appt-en',
      route: '/dashboard',
      variants: {
        populated: {
          anchor: 'upcoming-appointment-detail',
          speech: "Here is your 'Upcoming Appointment' section. When you add an appointment, it will appear here with full details and reminder alerts.",
        },
        empty: {
          anchor: 'add-appointment-button',
          speech: "Here is your 'Upcoming Appointment' section. When you add an appointment, it will appear here with full details and reminder alerts.",
        },
      },
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-meds-en',
      anchor: 'medications-reminders-card',
      route: '/dashboard',
      speech: "Here are your 'Medications & Reminders', showing active medicines and next dose time with an 'I Took It' button to log doses.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-family-en',
      anchor: 'family-overview-section',
      route: '/dashboard',
      speech: "Here is the 'Family Overview' section, allowing you to monitor the health, appointments, and medications of all your family members in one place.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-records-en',
      anchor: 'recent-records-card',
      route: '/dashboard',
      speech: "Here are your 'Recent Medical Records', showing your latest uploaded lab results, prescriptions, and medical scans with AI analysis.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },

    // ── Part 2: Medical Records Page ──
    {
      id: 'mr-welcome-en',
      route: '/medical-records',
      speech: "Now let's visit your 'Medical Records' page! Here I organize all your medical files, prescriptions, and reports.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'mr-search-en',
      anchor: 'mr-search-bar',
      route: '/medical-records',
      speech: "Here is the search & filter bar. Easily search for any prescription or lab report by name or doctor name.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-general-en',
      anchor: 'mr-card-general',
      route: '/medical-records',
      speech: "Here is the 'Medical Reports' category, displaying all general health summaries and medical documents.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-medicine-en',
      anchor: 'mr-card-medicine',
      route: '/medical-records',
      speech: "Here is the 'Medicines' category, displaying your uploaded medicine packages and dosage instructions.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-prescription-en',
      anchor: 'mr-card-prescription',
      route: '/medical-records',
      speech: "Here is the 'Prescriptions' category, displaying all prescriptions issued by doctors with smart medication extraction.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-imaging-en',
      anchor: 'mr-card-imaging',
      route: '/medical-records',
      speech: "Here is the 'Imaging' category, displaying medical imaging scans such as X-rays, MRI, CT scans, and ultrasound.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-lab-en',
      anchor: 'mr-card-lab',
      route: '/medical-records',
      speech: "Here is the 'Lab Tests' category, showing blood work results and lab measurements with AI health insights.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-recent-en',
      anchor: 'mr-recent-list',
      route: '/medical-records',
      speech: "Here is your 'Recent Records' list. Tap any record card to view, edit, or delete its full details.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-add-en',
      anchor: 'add-record-button',
      route: '/medical-records',
      speech: "Tap 'Add New Record' anytime to upload a new document via document scanner, camera, or file picker!",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 3: Appointments Page ──
    {
      id: 'appt-welcome-en',
      route: '/appointments',
      speech: "Now let's visit your 'Appointments' page! I will help you organize and track all your doctor visits and reminders.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'appt-upcoming-en',
      anchor: 'appts-upcoming-card',
      route: '/appointments',
      speech: "Here is your 'Upcoming Appointment' card, showing doctor name, medical specialty, and visit time.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-chips-en',
      anchor: 'appts-summary-chips',
      route: '/appointments',
      speech: "Here is a quick glance summary showing your upcoming, completed, and cancelled appointment counts.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-list-en',
      anchor: 'appts-upcoming-list',
      route: '/appointments',
      speech: "Here is your 'Upcoming Appointments' list, displaying all upcoming visits ordered chronologically.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-history-en',
      anchor: 'appts-history-section',
      route: '/appointments',
      speech: "Here is your 'Appointments History' section, allowing you to review past doctor visits and filter by month.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-settings-en',
      anchor: 'appts-reminder-settings',
      route: '/appointments',
      speech: "Here are your 'Reminder Settings', enabling reminder alerts and setting lead times (15 min, 1 hour, or 1 day).",
      speechLanguage: 'en-US',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'appt-add-en',
      anchor: 'add-appointment',
      route: '/appointments',
      speech: "Tap the floating '+' button at the bottom anytime to schedule a new doctor appointment!",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 4: Medications & Reminders Page ──
    {
      id: 'med-welcome-en',
      route: '/medications',
      speech: "Now let's visit your 'Medications & Reminders' page! I will help you set dosage schedules and alert notifications on time.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'med-add-btn-en',
      anchor: 'add-medication-btn',
      route: '/medications',
      speech: "Tap 'Add Medication' anytime to register new medicines, set dosages, and configure reminder times.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'med-today-en',
      anchor: 'med-today-glance',
      route: '/medications',
      speech: "Here is 'Today's Overview', displaying total daily doses, taken doses, remaining doses, and overdue alerts.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'med-active-list-en',
      anchor: 'med-active-list',
      route: '/medications',
      speech: "Here is your 'Active Medications' list, showing all pill containers with dosage instructions and next alert times.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 5: My Profile Page ──
    {
      id: 'profile-welcome-en',
      route: '/my-profile',
      speech: "Now let's visit your 'Profile' page! I will help you manage your personal details, health information, and account settings.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'profile-hero-en',
      anchor: 'profile-hero-card',
      route: '/my-profile',
      speech: "Here is your main profile card, displaying your profile photo, full name, email, and membership statistics.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-personal-btn-en',
      anchor: 'profile-personal-info',
      route: '/my-profile',
      speech: "Tap 'Personal Information' to edit your name, date of birth, phone number, and gender.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-health-btn-en',
      anchor: 'profile-health-info',
      route: '/my-profile',
      speech: "Tap 'Health Information' to manage blood type, height, weight, allergies, and chronic conditions.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-emergency-btn-en',
      anchor: 'profile-emergency-contacts',
      route: '/my-profile',
      speech: "Here are 'Emergency Contacts'. Save emergency contact numbers for instant SOS alert notifications.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-family-btn-en',
      anchor: 'profile-family-profiles',
      route: '/my-profile',
      speech: "Here are 'Family Profiles'. Add your family members' profiles and monitor their health metrics.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-settings-btn-en',
      anchor: 'profile-settings',
      route: '/my-profile',
      speech: "Here are 'Settings'. Tap here to change language, manage notifications, and update your account password.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-rate-btn-en',
      anchor: 'profile-rate-rafiq',
      route: '/my-profile',
      speech: "And don't forget to tap 'Rate Rafiq' and give us 5 stars to help us keep delivering the best healthcare experience for you!",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },

    // ── Part 6: Return to Dashboard & Spotlight Tour Button ──
    {
      id: 'welcome-finish-en',
      anchor: 'header-tour-btn',
      route: '/dashboard',
      speech: "We've now visited and seen every button and section across every single page! On any page, tap the tour button (?) in the top header to launch its dedicated detailed tour!",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
  onStart: () => console.log('[WelcomeTourEN] started'),
  onComplete: () => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('rafiq_tour_completed', 'true');
    }
  },
  onCancel: () => {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('rafiq_tour_completed', 'true');
    }
  },
};

// ── Dashboard Tour (English) ───────────────────────────────────────────────

export const DASHBOARD_TOUR_EN: TourScenario = {
  id: 'dashboard-tour-en',
  title: 'Dashboard Tour',
  description: 'Explore your health dashboard',
  category: 'onboarding',
  steps: [
    {
      id: 'dash-welcome-en',
      route: '/dashboard',
      speech: "Welcome {{userName}} to your health dashboard! I'll guide you through each section and action in detail.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'dash-ai-summary-en',
      anchor: 'ai-health-summary-card',
      route: '/dashboard',
      speech: "Here is your daily AI Health Summary and personalized medical recommendations.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-ai-details-btn-en',
      anchor: 'ai-summary-details-btn',
      route: '/dashboard',
      speech: "Tap 'Ask AI for details' to ask me to explain any specific item in your summary.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-today-schedule-en',
      anchor: 'today-schedule-section',
      route: '/dashboard',
      speech: "Here is the 'Today' section showing your upcoming appointments, medication doses, and water intake.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'dash-qa-upload-en',
      anchor: 'qa-upload-record',
      route: '/dashboard',
      speech: "Tap 'Upload Record' to scan lab tests or prescriptions with AI.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-appointments-en',
      anchor: 'qa-appointments',
      route: '/dashboard',
      speech: "Tap 'Appointments' to schedule doctor visits and manage reminders.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-reminders-en',
      anchor: 'qa-reminders',
      route: '/dashboard',
      speech: "Tap 'Reminders' to manage pill schedules and set dose lead times.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-qa-aichat-en',
      anchor: 'ai-chat-quick-action',
      route: '/dashboard',
      speech: "Tap 'AI Chat' to talk with me via voice or text chat anytime.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'dash-qa-family-en',
      anchor: 'qa-family',
      route: '/dashboard',
      speech: "Tap 'Family' to manage health profiles and medications for all family members.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-upcoming-appt-en',
      route: '/dashboard',
      variants: {
        populated: {
          anchor: 'upcoming-appointment-detail',
          speech: "Here are the details of your upcoming doctor appointment.",
        },
        empty: {
          anchor: 'add-appointment-button',
          speech: "Here is your upcoming appointment section. When you add an appointment, it will appear here.",
        },
      },
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-meds-en',
      anchor: 'medications-reminders-card',
      route: '/dashboard',
      speech: "Here are your active medications and daily dose reminders.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'dash-family-en',
      anchor: 'family-overview-section',
      route: '/dashboard',
      speech: "Here is a quick look at the health status of your family members.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
    {
      id: 'dash-records-en',
      anchor: 'recent-records-card',
      route: '/dashboard',
      speech: "And here are your most recently added medical records and lab reports.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
  ],
};

// ── Medical Records Tour (English) ────────────────────────────────────────

export const MEDICAL_RECORDS_TOUR_EN: TourScenario = {
  id: 'medical-records-tour-en',
  title: 'Medical Records Tour',
  description: 'Explore the Medical Records page in detail',
  category: 'onboarding',
  steps: [
    {
      id: 'mr-welcome-en',
      route: '/medical-records',
      speech: "Welcome to your Medical Records page! I will help you organize and analyze all your medical documents here.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'mr-search-en',
      anchor: 'mr-search-bar',
      route: '/medical-records',
      speech: "Here is the Search & Filter bar. Use it to quickly find any lab result or prescription by document name or doctor name.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-general-en',
      anchor: 'mr-card-general',
      route: '/medical-records',
      speech: "Here is 'Medical Reports'. It organizes all your uploaded general medical summaries, discharge letters, and reports.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-medicine-en',
      anchor: 'mr-card-medicine',
      route: '/medical-records',
      speech: "Here is 'Medications'. It displays all scanned medicine boxes and dose instructions.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-prescription-en',
      anchor: 'mr-card-prescription',
      route: '/medical-records',
      speech: "Here is 'Prescriptions'. It contains all your doctor prescriptions with automatic AI medication extraction.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-imaging-en',
      anchor: 'mr-card-imaging',
      route: '/medical-records',
      speech: "Here is 'Imaging & X-Rays'. It stores all X-ray scans, MRI scans, and ultrasound imaging.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-lab-en',
      anchor: 'mr-card-lab',
      route: '/medical-records',
      speech: "Here is 'Lab Analysis'. It stores all your blood tests and lab results complete with AI status analysis.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'mr-recent-en',
      anchor: 'mr-recent-list',
      route: '/medical-records',
      speech: "Here is your 'Recent Records' list. Tap any record item to view its full details, preview attached documents, or edit entries.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'mr-add-en',
      anchor: 'add-record-button',
      route: '/medical-records',
      speech: "And here is 'Add New Record'! Tap it anytime to scan a document with AI, take a camera photo, upload a file, or enter details manually.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── Appointments Tour (English) ────────────────────────────────────────────

export const APPOINTMENTS_TOUR_EN: TourScenario = {
  id: 'appointments-tour-en',
  title: 'Appointments Tour',
  description: 'Explore the Appointments page in detail',
  category: 'onboarding',
  steps: [
    {
      id: 'appt-welcome-en',
      route: '/appointments',
      speech: "Welcome to your Appointments page! I will help you organize, track, and receive alerts for all your doctor visits here.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'appt-upcoming-en',
      anchor: 'appts-upcoming-card',
      route: '/appointments',
      speech: "Here is your 'Upcoming Appointment' card. It shows the doctor's name, specialty, clinic location, and scheduled date.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-chips-en',
      anchor: 'appts-summary-chips',
      route: '/appointments',
      speech: "Here is a quick overview showing counts for upcoming, completed, missed, and cancelled appointments.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-list-en',
      anchor: 'appts-upcoming-list',
      route: '/appointments',
      speech: "Here is your 'Upcoming Appointments' list. It displays your scheduled doctor visits chronologically.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'appt-history-en',
      anchor: 'appts-history-section',
      route: '/appointments',
      speech: "Here is your 'Appointment History' section. Review past doctor visits and filter entries by month.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'appt-settings-en',
      anchor: 'appts-reminder-settings',
      route: '/appointments',
      speech: "Here are your 'Reminder Settings'. Toggle notifications and customize alert lead times 15 mins, 1 hour, or 1 day before visits.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'appt-add-en',
      anchor: 'add-appointment',
      route: '/appointments',
      speech: "And here is the floating '+' button at the bottom! Tap it anytime to schedule a new doctor appointment and set reminder alerts!",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── Medications Tour (English) ─────────────────────────────────────────────

export const MEDICATIONS_TOUR_EN: TourScenario = {
  id: 'medications-tour-en',
  title: 'Medications Tour',
  description: 'Explore the Medications & Reminders page in detail',
  category: 'onboarding',
  steps: [
    {
      id: 'med-welcome-en',
      route: '/medications',
      speech: "Welcome to your Medications & Reminders page! I will help you schedule dose alerts and manage all your active medicines here.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'med-add-btn-en',
      anchor: 'add-medication-btn',
      route: '/medications',
      speech: "Tap 'Add Medication' anytime to register a new medicine, set dose times, and configure reminder alerts.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'med-today-en',
      anchor: 'med-today-glance',
      route: '/medications',
      speech: "Here is 'Today's Overview'. It tracks today's total doses, taken doses, due doses, and overdue alerts.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'med-active-list-en',
      anchor: 'med-active-list',
      route: '/medications',
      speech: "Here is your 'Active Medications' list. View dosage instructions, frequency, and upcoming reminder times for all your medicines.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── Family Profiles Tour (English) ────────────────────────────────────────

export const FAMILY_PROFILES_TOUR_EN: TourScenario = {
  id: 'family-profiles-tour-en',
  title: 'Family Profiles Tour',
  description: 'Explore the Family Profiles page',
  category: 'onboarding',
  steps: [
    {
      id: 'family-list-en',
      anchor: 'family-profiles-list',
      route: '/family-profiles',
      speech: "Here you can view and switch between all registered family members.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
      highlight: true,
    },
    {
      id: 'family-add-btn-en',
      anchor: 'add-family-profile',
      route: '/family-profiles',
      speech: "Press 'Add Family Member' to create a new profile and monitor their health together.",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

// ── My Profile Tour (English) ──────────────────────────────────────────────

export const MY_PROFILE_TOUR_EN: TourScenario = {
  id: 'my-profile-tour-en',
  title: 'My Profile Tour',
  description: 'Explore your personal profile and account settings in detail',
  category: 'onboarding',
  steps: [
    {
      id: 'profile-welcome-en',
      route: '/my-profile',
      speech: "Welcome to your Profile page! Here you can manage your personal details, health information, and account settings.",
      speechLanguage: 'en-US',
      avatarState: 'wave',
    },
    {
      id: 'profile-hero-en',
      anchor: 'profile-hero-card',
      route: '/my-profile',
      speech: "Here is your main profile card displaying your photo, name, email, and membership statistics.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-personal-btn-en',
      anchor: 'profile-personal-info',
      route: '/my-profile',
      speech: "Tap 'Personal Information' to update your date of birth, phone number, and gender.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-health-btn-en',
      anchor: 'profile-health-info',
      route: '/my-profile',
      speech: "Tap 'Health Information' to update your blood type, height, weight, allergies, and chronic conditions.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-emergency-btn-en',
      anchor: 'profile-emergency-contacts',
      route: '/my-profile',
      speech: "Tap 'Emergency Contacts' to add trusted emergency contact numbers for instant SOS notifications.",
      speechLanguage: 'en-US',
      avatarState: 'pointLeft',
      highlight: true,
    },
    {
      id: 'profile-family-btn-en',
      anchor: 'profile-family-profiles',
      route: '/my-profile',
      speech: "Tap 'Family Profiles' to add family members and manage their health records.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-settings-btn-en',
      anchor: 'profile-settings',
      route: '/my-profile',
      speech: "Tap 'Settings' to change app language, manage notifications, or update your password.",
      speechLanguage: 'en-US',
      avatarState: 'thinking',
      highlight: true,
    },
    {
      id: 'profile-rate-btn-en',
      anchor: 'profile-rate-rafiq',
      route: '/my-profile',
      speech: "And finally, don't forget to tap 'Rate Rafiq' and give us 5 stars to help us keep delivering the best healthcare experience for you!",
      speechLanguage: 'en-US',
      avatarState: 'celebrate',
      highlight: true,
    },
  ],
};

export const DEFAULT_TOURS_EN: TourScenario[] = [
  ONBOARDING_TOUR_EN,
  WELCOME_TOUR_EN,
  DASHBOARD_TOUR_EN,
  MEDICAL_RECORDS_TOUR_EN,
  APPOINTMENTS_TOUR_EN,
  MEDICATIONS_TOUR_EN,
  FAMILY_PROFILES_TOUR_EN,
  MY_PROFILE_TOUR_EN,
];
