export const adminCopy = {
  en: {
    brand: 'Rafiq Control',
    workspace: 'Administration',
    search: 'Search the admin portal...',
    menu: 'Open navigation',
    close: 'Close navigation',
    notifications: 'Notifications',
    language: 'Switch to Arabic',
    theme: 'Toggle dark mode',
    logout: 'Logout',
    profile: 'Admin profile',
    nav: {
      dashboard: 'Dashboard',
      users: 'Users',
      doctors: 'Doctors',
      families: 'Families',
      medicalRecords: 'Medical Records',
      appointments: 'Appointments',
      medications: 'Medications',
      notifications: 'Notifications',
      documents: 'Documents',
      aiAnalysis: 'AI Analysis',
      statistics: 'Statistics',
      settings: 'System Settings',
      auditLogs: 'Audit Logs',
      profile: 'Profile'
    },
    dashboard: {
      title: 'System overview',
      subtitle: 'Monitor adoption, care activity, and platform health from one place.',
      live: 'Live platform data',
      totalUsers: 'Total users',
      activeUsers: 'Active users',
      profiles: 'Health profiles',
      managedProfiles: 'Managed profiles',
      appointmentsToday: 'Appointments today',
      monthlyAppointments: 'Appointments this month',
      pendingAppointments: 'Pending appointments',
      completedAppointments: 'Completed appointments',
      remindersToday: 'Reminders today',
      documents: 'Medical documents',
      aiConversations: 'AI conversations',
      newRegistrations: 'New registrations',
      monthlyGrowth: 'monthly growth',
      userGrowth: 'User growth',
      appointmentVolume: 'Appointment volume',
      lastSixMonths: 'Last six months',
      genderDistribution: 'Profile distribution',
      recentUsers: 'Recent registrations',
      recentAppointments: 'Recent appointments',
      viewUsers: 'View all users',
      patient: 'Patient',
      provider: 'Provider',
      date: 'Date',
      status: 'Status',
      noData: 'No activity is available yet.',
      retry: 'Retry',
      loadError: 'Dashboard data could not be loaded.'
    },
    users: {
      title: 'User management',
      subtitle: 'Search, review, and control access to Rafiq accounts.',
      total: 'users',
      search: 'Search by name, email, or phone',
      allStatuses: 'All statuses',
      active: 'Active',
      inactive: 'Inactive',
      allRoles: 'All roles',
      newest: 'Newest first',
      oldest: 'Oldest first',
      name: 'Name',
      email: 'Email',
      account: 'Account',
      role: 'Role',
      joined: 'Joined',
      profile: 'Health profile',
      actions: 'Actions',
      available: 'Available',
      missing: 'Not created',
      activate: 'Activate',
      deactivate: 'Deactivate',
      activating: 'Activating...',
      deactivating: 'Deactivating...',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
      emptyTitle: 'No users match these filters',
      emptyBody: 'Try clearing a filter or using a different search term.',
      loadError: 'Users could not be loaded.',
      updateError: 'The account status could not be updated.',
      confirmDeactivate: 'Deactivate this account? The user will lose access until it is reactivated.',
      cancel: 'Cancel',
      confirm: 'Confirm deactivation'
    },
    placeholder: {
      title: 'Module foundation ready',
      body: 'This destination is connected to the protected admin workspace and is ready for its dedicated API and workflow in the next implementation phase.',
      back: 'Back to dashboard'
    }
  },
  ar: {
    brand: 'إدارة رفيق',
    workspace: 'لوحة الإدارة',
    search: 'ابحث في لوحة الإدارة...',
    menu: 'فتح القائمة',
    close: 'إغلاق القائمة',
    notifications: 'الإشعارات',
    language: 'التبديل إلى الإنجليزية',
    theme: 'تبديل الوضع الداكن',
    logout: 'تسجيل الخروج',
    profile: 'ملف المدير',
    nav: {
      dashboard: 'لوحة التحكم',
      users: 'المستخدمون',
      doctors: 'الأطباء',
      families: 'العائلات',
      medicalRecords: 'السجلات الطبية',
      appointments: 'المواعيد',
      medications: 'الأدوية',
      notifications: 'الإشعارات',
      documents: 'المستندات',
      aiAnalysis: 'تحليلات الذكاء الاصطناعي',
      statistics: 'الإحصائيات',
      settings: 'إعدادات النظام',
      auditLogs: 'سجل التدقيق',
      profile: 'الملف الشخصي'
    },
    dashboard: {
      title: 'نظرة عامة على النظام',
      subtitle: 'تابع الاستخدام ونشاط الرعاية وصحة المنصة من مكان واحد.',
      live: 'بيانات مباشرة من المنصة',
      totalUsers: 'إجمالي المستخدمين',
      activeUsers: 'المستخدمون النشطون',
      profiles: 'الملفات الصحية',
      managedProfiles: 'الملفات المُدارة',
      appointmentsToday: 'مواعيد اليوم',
      monthlyAppointments: 'مواعيد هذا الشهر',
      pendingAppointments: 'المواعيد المعلقة',
      completedAppointments: 'المواعيد المكتملة',
      remindersToday: 'تذكيرات اليوم',
      documents: 'المستندات الطبية',
      aiConversations: 'محادثات الذكاء الاصطناعي',
      newRegistrations: 'التسجيلات الجديدة',
      monthlyGrowth: 'نمو شهري',
      userGrowth: 'نمو المستخدمين',
      appointmentVolume: 'حجم المواعيد',
      lastSixMonths: 'آخر ستة أشهر',
      genderDistribution: 'توزيع الملفات',
      recentUsers: 'أحدث التسجيلات',
      recentAppointments: 'أحدث المواعيد',
      viewUsers: 'عرض كل المستخدمين',
      patient: 'المريض',
      provider: 'مقدم الخدمة',
      date: 'التاريخ',
      status: 'الحالة',
      noData: 'لا يوجد نشاط متاح بعد.',
      retry: 'إعادة المحاولة',
      loadError: 'تعذر تحميل بيانات لوحة التحكم.'
    },
    users: {
      title: 'إدارة المستخدمين',
      subtitle: 'ابحث وراجع وتحكم في صلاحية الدخول إلى حسابات رفيق.',
      total: 'مستخدم',
      search: 'بحث بالاسم أو البريد أو الهاتف',
      allStatuses: 'كل الحالات',
      active: 'نشط',
      inactive: 'غير نشط',
      allRoles: 'كل الأدوار',
      newest: 'الأحدث أولاً',
      oldest: 'الأقدم أولاً',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      account: 'الحساب',
      role: 'الدور',
      joined: 'تاريخ الانضمام',
      profile: 'الملف الصحي',
      actions: 'الإجراءات',
      available: 'متاح',
      missing: 'غير منشأ',
      activate: 'تفعيل',
      deactivate: 'إيقاف',
      activating: 'جارٍ التفعيل...',
      deactivating: 'جارٍ الإيقاف...',
      previous: 'السابق',
      next: 'التالي',
      page: 'صفحة',
      of: 'من',
      emptyTitle: 'لا يوجد مستخدمون مطابقون',
      emptyBody: 'جرّب مسح أحد الفلاتر أو استخدام عبارة بحث مختلفة.',
      loadError: 'تعذر تحميل المستخدمين.',
      updateError: 'تعذر تحديث حالة الحساب.',
      confirmDeactivate: 'هل تريد إيقاف هذا الحساب؟ سيفقد المستخدم إمكانية الدخول حتى إعادة تفعيله.',
      cancel: 'إلغاء',
      confirm: 'تأكيد الإيقاف'
    },
    placeholder: {
      title: 'أساس الوحدة جاهز',
      body: 'هذه الوجهة متصلة بمساحة الإدارة المحمية وجاهزة لواجهات API وسير العمل الخاص بها في مرحلة التنفيذ التالية.',
      back: 'العودة إلى لوحة التحكم'
    }
  }
} as const;
