export const adminCopy = {
  en: {
    brand: 'Rafiq Control',
    workspace: 'Administration',
    search: 'Search the admin portal...',
    menu: 'Open navigation',
    close: 'Close navigation',
    notifications: 'Notifications',
    language: 'Switch to Arabic',
    theme: 'Toggle dark mode',
    logout: 'Logout',
    profile: 'Admin profile',
    nav: {
      dashboard: 'Dashboard',
      users: 'Users',
      families: 'Families',
      aiOperations: 'AI Operations',
      medicalRecords: 'Medical Records',
      medications: 'Medications',
      appointments: 'Appointments',
      documents: 'Documents',
      analytics: 'Analytics',
      settings: 'System Settings',
      auditLogs: 'Audit Logs',
      reviews: 'App Reviews'
    },
    dashboard: {
      title: 'System overview',
      subtitle: 'Monitor adoption, care activity, and platform health from one place.',
      live: 'Live platform data',
      totalUsers: 'Total users',
      activeUsers: 'Active users',
      profiles: 'Health profiles',
      managedProfiles: 'Managed profiles',
      appointmentsToday: 'Appointments today',
      monthlyAppointments: 'Appointments this month',
      pendingAppointments: 'Pending appointments',
      completedAppointments: 'Completed appointments',
      remindersToday: 'Reminders today',
      documents: 'Medical documents',
      aiConversations: 'AI conversations',
      newRegistrations: 'New registrations',
      monthlyGrowth: 'monthly growth',
      userGrowth: 'User growth',
      appointmentVolume: 'Appointment volume',
      lastSixMonths: 'Last six months',
      genderDistribution: 'Profile distribution',
      recentUsers: 'Recent registrations',
      recentAppointments: 'Recent appointments',
      viewUsers: 'View all users',
      patient: 'Patient',
      provider: 'Provider',
      date: 'Date',
      status: 'Status',
      noData: 'No activity is available yet.',
      retry: 'Retry',
      loadError: 'Dashboard data could not be loaded.',
      reviewStatsTitle: 'App Reviews Summary',
      reviewStatsAvg: 'Average Rating',
      reviewStatsTotal: 'Total Reviews',
      totalAiRequests: 'Total AI requests',
      flaggedAiRequests: 'Flagged AI requests',
      aiUsage: 'AI Usage Overview',
      mostActiveUser: 'Most active user',
      usersNeedAttention: 'Users needing attention',
      reason: 'Reason',
      actionView: 'View user',
      reviewStatsVisible: 'Visible',
      reviewStatsHidden: 'Hidden',
      reviewStatsViewAll: 'Manage Reviews'
    },
    reviews: {
      title: 'App Reviews',
      subtitle: 'Monitor satisfaction, analyze feedback trends, and manage every review through its lifecycle.',
      healthScore: 'Health Score',
      healthScoreDesc: 'Recency-weighted satisfaction index (0-100)',
      totalReviews: 'Total Reviews',
      pendingReviews: 'Pending Attention',
      positiveRate: 'Positive Rate',
      positiveRateDesc: '% of 4-5 star reviews',
      thisWeek: 'This Week',
      withReply: 'Replied',
      avgRating: 'Avg Rating',
      trendTitle: 'Rating Trend',
      trendDesc: 'Monthly average rating over the last 6 months',
      categoryTitle: 'By Category',
      distTitle: 'Star Distribution',
      filterAll: 'All',
      filterPending: 'Pending',
      filterReviewed: 'Reviewed',
      filterResolved: 'Resolved',
      filterArchived: 'Archived',
      sortNewest: 'Newest',
      sortOldest: 'Oldest',
      sortStarsAsc: 'Stars asc',
      sortStarsDesc: 'Stars desc',
      allCategories: 'All categories',
      allStars: 'All ratings',
      catGeneral: 'General',
      catBugReport: 'Bug Report',
      catFeatureRequest: 'Feature Request',
      catPerformance: 'Performance',
      catUiUx: 'UI / UX',
      catContentQuality: 'Content Quality',
      statusPending: 'Pending',
      statusReviewed: 'Reviewed',
      statusResolved: 'Resolved',
      statusArchived: 'Archived',
      tableTitle: 'Reviews',
      colUser: 'User',
      colStars: 'Rating',
      colCategory: 'Category',
      colStatus: 'Status',
      colComment: 'Comment',
      colDate: 'Date',
      colActions: 'Actions',
      detailTitle: 'Review Detail',
      detailMeta: 'Metadata',
      detailDevice: 'Device',
      detailVersion: 'Version',
      detailLanguage: 'Language',
      adminNotes: 'Internal Notes',
      adminNotesPlaceholder: 'Add private notes visible only to admins...',
      saveNotes: 'Save Notes',
      replyTitle: 'Reply to User',
      replyPlaceholder: 'Write a reply that will be sent as an in-app notification...',
      sendReply: 'Send Reply',
      updateReply: 'Update Reply',
      clearReply: 'Clear Reply',
      repliedAt: 'Replied',
      quickReplies: 'Quick Replies',
      qr1: 'Thank you for your feedback - we have logged this for our team.',
      qr2: 'We are looking into this issue and will update you soon.',
      qr3: 'This feature is on our roadmap. Thanks for the suggestion!',
      qr4: 'We are sorry for the experience. Our team is working on a fix.',
      visible: 'Visible',
      hidden: 'Hidden',
      show: 'Make Public',
      hide: 'Hide from Public',
      delete: 'Delete',
      markReviewed: 'Mark Reviewed',
      markResolved: 'Mark Resolved',
      markArchived: 'Archive',
      markPending: 'Reset to Pending',
      viewDetail: 'Open',
      closeDetail: 'Close',
      noComment: 'No comment provided',
      empty: 'No reviews match your filters.',
      emptyAll: 'No reviews yet.',
      loadError: 'Reviews could not be loaded.',
      retry: 'Retry',
      saving: 'Saving...',
      saved: 'Saved',
      deleteConfirm: 'Delete this review permanently? This cannot be undone.',
      cancel: 'Cancel',
      confirm: 'Delete',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of'
    },
    users: {
      title: 'User management',
      subtitle: 'Search, review, and control access to Rafiq accounts.',
      total: 'users',
      search: 'Search by name, email, or phone',
      allStatuses: 'All statuses',
      active: 'Active',
      inactive: 'Inactive',
      allRoles: 'All roles',
      newest: 'Newest first',
      oldest: 'Oldest first',
      name: 'Name',
      email: 'Email',
      account: 'Account',
      role: 'Role',
      joined: 'Joined',
      profile: 'Health profile',
      actions: 'Actions',
      available: 'Available',
      missing: 'Not created',
      activate: 'Activate',
      deactivate: 'Deactivate',
      activating: 'Activating...',
      deactivating: 'Deactivating...',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
      emptyTitle: 'No users match these filters',
      emptyBody: 'Try clearing a filter or using a different search term.',
      loadError: 'Users could not be loaded.',
      updateError: 'The account status could not be updated.',
      confirmDeactivate: 'Deactivate this account? The user will lose access until it is reactivated.',
      cancel: 'Cancel',
      confirm: 'Confirm deactivation'
    },
    auditLogs: {
      title: 'Audit Logs',
      subtitle: 'Track important administrative and system activities across the platform.',
      totalLogs:     'Total Logs',
      todayActivity: "Today's Activities",
      criticalEvents:'Critical Events',
      adminActions:  'Admin Actions',
      activitySummary: 'Activity Summary',
      infoEvents:    'Information',
      successEvents: 'Success',
      warningEvents: 'Warning',
      criticalCount: 'Critical',
      searchPlaceholder: 'Search by action, actor, or target…',
      allModules:    'All modules',
      allSeverities: 'All severities',
      filterFrom:    'From date',
      filterTo:      'To date',
      clearFilters:  'Clear filters',
      colTime:       'Time',
      colActor:      'Performed By',
      colModule:     'Module',
      colAction:     'Action',
      colTarget:     'Target',
      colSeverity:   'Severity',
      view:          'View',
      drawerTitle:       'Activity Details',
      drawerTimestamp:   'Timestamp',
      drawerActor:       'Performed By',
      drawerModule:      'Module',
      drawerTarget:      'Target',
      drawerSeverity:    'Severity',
      drawerDescription: 'Description',
      drawerChanges:     'Changes',
      drawerBefore:      'Before',
      drawerAfter:       'After',
      drawerNoChanges:   'No field changes were recorded for this action.',
      close:             'Close',
      severityInfo:     'Information',
      severitySuccess:  'Success',
      severityWarning:  'Warning',
      severityCritical: 'Critical',
      moduleUsers:   'Users',
      moduleReviews: 'App Reviews',
      moduleAiOps:   'AI Operations',
      moduleSettings:'Settings',
      moduleSystem:  'System',
      empty:    'No activity logs match your filters.',
      emptyAll: 'No activity has been recorded yet.',
      loadError:'Activity logs could not be loaded.',
      retry:    'Retry',
      previous: 'Previous',
      next:     'Next',
      page:     'Page',
      of:       'of',
      actionUserActivated:   'User Activated',
      actionUserSuspended:   'User Suspended',
      actionRoleChanged:     'Role Changed',
      actionFeedbackReviewed:'Feedback Reviewed',
      actionFeedbackResolved:'Feedback Resolved',
      actionReviewHidden:    'Review Hidden',
      actionReviewPublished: 'Review Published',
      actionMaintenanceEnabled: 'Maintenance Mode Enabled',
      actionConfigChanged:   'Configuration Changed',
    },
    placeholder: {
      title: 'Module foundation ready',
      body: 'This destination is connected to the protected admin workspace and is ready for its dedicated API and workflow in the next implementation phase.',
      back: 'Back to dashboard'
    },
    aiOps: {
      title: 'AI Operations',
      subtitle: 'Continuously monitor, evaluate, and improve AI quality and reliability.',
      tabOverview: 'Overview',
      tabConversations: 'Conversations',
      tabFeedback: 'Feedback',
      tabPerformance: 'Performance',

      // ── Overview ──────────────────────────────────────────────────────
      healthScore: 'AI Health Score',
      healthGood: 'Healthy',
      healthFair: 'Needs attention',
      healthPoor: 'Degraded',
      healthScoreFormula: 'Score = (7-day Success Rate × 65%) + (Positive Rating × 35%)',
      healthScoreDesc: 'Composite quality signal. A score of 85+ is healthy, 70–84 needs attention, below 70 is degraded.',
      positiveRate: 'Positive rating',
      unreviewedNegative: 'Unreviewed negative',
      failedLast7d: 'Failed (7 days)',
      avgResponseTime: 'Avg response time',
      requestsToday: 'Requests today',
      chatConversations: 'Chat conversations',
      voiceSessions: 'Voice sessions',
      qualityTrend: 'Quality trend',
      last7Days: 'Last 7 days',
      requests: 'Requests',
      failures: 'Failures',
      thumbsUpShort: '👍',
      thumbsDownShort: '👎',

      // ── Insights ──────────────────────────────────────────────────────
      insights: 'AI Insights',
      insightsSub: 'Key findings from the last 30 days',
      mostUsedFeature: 'Most Used Feature',
      mostReportedCategory: 'Most Reported Issue',
      highestErrorFeature: 'Highest Error Source',
      slowestFeature: 'Slowest Feature',
      fastestFeature: 'Fastest Feature',
      insightRequests: 'requests',
      insightErrors: 'errors',
      insightAvgMs: 'avg',
      insightOccurrences: 'occurrences',
      noInsights: 'Not enough data yet.',

      // ── Incidents ─────────────────────────────────────────────────────
      incidents: 'Active Incidents',
      incidentsSub: 'Automated alerts based on current metrics',
      incidentHighError: 'High failure rate',
      incidentHighErrorDesc: 'More than 20 failed requests in the last 7 days.',
      incidentLowRating: 'Low positive rating',
      incidentLowRatingDesc: 'User satisfaction is below 60%. Review negative feedback immediately.',
      incidentPendingReviews: 'Unreviewed negative feedback',
      incidentPendingReviewsDesc: 'More than 10 negative items are waiting for admin review.',
      incidentSlowResponse: 'High average response time',
      incidentSlowResponseDesc: 'Average AI response time exceeds 10 seconds.',
      noIncidents: 'No active incidents — AI is operating normally.',
      severityCritical: 'Critical',
      severityWarning: 'Warning',

      // ── Conversations ──────────────────────────────────────────────────
      user: 'User',
      feature: 'Feature',
      model: 'Model',
      duration: 'Duration',
      status: 'Status',
      date: 'Date',
      success: 'Success',
      failed: 'Failed',
      searchPlaceholder: 'Search by user or feature…',
      allFeatures: 'All features',
      allStatuses: 'All statuses',
      noRequests: 'No AI requests recorded yet.',
      noRequestsSub: 'Telemetry accrues once users start using AI features.',
      // Drawer
      requestDetail: 'Request detail',
      close: 'Close',
      userPrompt: 'User prompt',
      aiResponse: 'AI response',
      errorInfo: 'Error information',
      noConversation: 'No conversation linked to this request.',
      requestMeta: 'Request metadata',
      clickRowHint: 'Click any row to inspect the request.',

      // ── Feedback ──────────────────────────────────────────────────────
      allReactions: 'All reactions',
      positive: 'Positive',
      negative: 'Negative',
      allTriageStatuses: 'All statuses',
      statusNew: 'New',
      statusInvestigating: 'Investigating',
      statusResolved: 'Resolved',
      statusIgnored: 'Ignored',
      allCategories: 'All categories',
      catHallucination: 'Hallucination',
      catWrongMedical: 'Wrong Medical Advice',
      catOcrIssue: 'OCR Issue',
      catVoice: 'Voice Recognition',
      catPerformance: 'Performance',
      catBug: 'Bug',
      catFeatureRequest: 'Feature Request',
      catOther: 'Other',
      dateFrom: 'From',
      dateTo: 'To',
      // Compact row
      reaction: 'Reaction',
      uncategorized: 'Uncategorized',
      expand: 'Expand',
      collapse: 'Collapse',
      // Expanded panel
      userQuestion: 'User question',
      noUserQuestion: 'User question not available.',
      aiMessage: 'AI message',
      userComment: 'User comment',
      noComment: 'No comment provided.',
      adminReview: 'Admin review',
      category: 'Category',
      triageStatus: 'Review status',
      adminNotes: 'Internal notes',
      adminNotesPlaceholder: 'Internal notes for this review (not visible to users)…',
      saveReview: 'Save review',
      saving: 'Saving…',
      feedbackContextHeader: 'Full conversation context — review the user question and AI response together to assess quality.',
      noFeedback: 'No feedback recorded yet.',
      noFeedbackSub: 'Feedback appears here when users rate AI responses.',

      // ── Performance ───────────────────────────────────────────────────
      dailyRequests: 'Daily request volume',
      errorRate: 'Error rate',
      errorRateDesc: 'Percentage of requests that returned an error.',
      slowRequests: 'Slow requests (>5 s)',
      slowRequestsDesc: 'Requests that took longer than 5 seconds to complete.',
      p95Latency: 'P95 latency',
      p95LatencyDesc: '95% of requests completed within this response time. A high P95 indicates occasional slow outliers.',
      avgLatency: 'Avg latency',
      avgLatencyDesc: 'Mean response time across all AI requests in the selected period.',
      requestsByFeature: 'Requests by feature',
      last30Days: 'Last 30 days',
      noPerformanceData: 'No performance data yet.',

      // ── Usage Intelligence ─────────────────────────────────────────────
      tabUsageIntelligence: 'Usage Intelligence',
      uiTitle: 'Usage Intelligence',
      uiSubtitle: 'Monitor AI resource consumption and identify unusual usage patterns.',
      uiTotalRequests: 'Total AI Requests',
      uiFlaggedRequests: 'Flagged Requests',
      uiUsersToReview: 'Users Needing Review',
      uiWarningsSent: 'Warnings Sent',
      uiAttentionQueue: 'Attention Queue',
      uiAttentionQueueSub: 'Users with flagged AI requests, ordered by severity',
      uiColUser: 'User',
      uiColTotalReq: 'Total Requests',
      uiColFlagged: 'Flagged',
      uiColWarnings: 'Warnings',
      uiColLastActivity: 'Last Activity',
      uiColActions: 'Actions',
      uiViewDetail: 'Review',
      uiEmptyQueue: 'No users with flagged requests.',
      uiEmptyQueueSub: 'The attention queue is clear — all AI usage appears normal.',
      uiUserDetail: 'User Activity Detail',
      uiUserDetailSub: 'AI-flagged requests for this user',
      uiColRequestType: 'Request Type',
      uiColUserRequest: 'User Request',
      uiColAiResponse: 'AI Response',
      uiColClassification: 'Classification',
      uiColReason: 'Reason',
      uiColDate: 'Date',
      uiNoFlagged: 'No flagged requests for this user.',
      uiActionHistory: 'Admin Action History',
      uiNoActions: 'No actions have been taken yet.',
      uiColAction: 'Action',
      uiColAdmin: 'Admin',
      uiColNotes: 'Notes',
      uiSendWarning: 'Send Warning',
      uiSendFinalWarning: 'Send Final Warning',
      uiRestrictAi: 'Restrict AI Access',
      uiRemoveAiRestriction: 'Remove AI Restriction',
      uiRestrictAccount: 'Restrict Account',
      uiRemoveAccountRestriction: 'Remove Account Restriction',
      uiSuspendAccount: 'Suspend Account',
      uiUnsuspendAccount: 'Unsuspend Account',
      uiActionNotes: 'Notes (optional)',
      uiActionNotesPlaceholder: 'Add a reason or note for this action...',
      uiConfirmAction: 'Confirm',
      uiCancelAction: 'Cancel',
      uiActionSending: 'Sending...',
      uiActionSuccess: 'Action completed successfully.',
      uiActionError: 'Action could not be completed.',
      uiBack: 'Back to Queue',
      uiStatusAiRestricted: 'AI Restricted',
      uiStatusRestricted: 'Account Restricted',
      uiStatusSuspended: 'Suspended',
      uiClassNonMedical: 'Non-Medical Upload',
      uiClassWrongType: 'Wrong Document Type',
      uiClassOffDomainChat: 'Off-Domain Chat',
      uiClassOffDomainVoice: 'Off-Domain Voice',
      uiClassPolicyViolation: 'Policy Violation',
      uiActionWarning: 'Warning',
      uiActionFinalWarning: 'Final Warning',
      uiActionRestrictAi: 'AI Restricted',
      uiActionRemoveAiRestriction: 'AI Restriction Removed',
      uiActionRestrictAccount: 'Account Restricted',
      uiActionRemoveAccountRestriction: 'Account Restriction Removed',
      uiActionSuspend: 'Account Suspended',
      uiActionUnsuspend: 'Account Unsuspended',
      uiLoadingUser: 'Loading user detail...',

      // ── Common ─────────────────────────────────────────────────────────
      loadError: 'Data could not be loaded.',
      retry: 'Retry',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
      ms: 'ms',
      pct: '%'
    }
  },
  ar: {
    brand: 'إدارة رفيق',
    workspace: 'لوحة الإدارة',
    search: 'ابحث في لوحة الإدارة...',
    menu: 'فتح القائمة',
    close: 'إغلاق القائمة',
    notifications: 'الإشعارات',
    language: 'التبديل إلى الإنجليزية',
    theme: 'تبديل الوضع الداكن',
    logout: 'تسجيل الخروج',
    profile: 'ملف المدير',
    nav: {
      dashboard: 'لوحة التحكم',
      users: 'المستخدمون',
      families: 'العائلات',
      aiOperations: 'عمليات الذكاء الاصطناعي',
      medicalRecords: 'السجلات الطبية',
      medications: 'الأدوية',
      appointments: 'المواعيد',
      documents: 'المستندات',
      analytics: 'الإحصائيات',
      settings: 'إعدادات النظام',
      auditLogs: 'سجل التدقيق',
      reviews: 'تقييمات التطبيق'
    },
    dashboard: {
      title: 'نظرة عامة على النظام',
      subtitle: 'تابع الاستخدام ونشاط الرعاية وصحة المنصة من مكان واحد.',
      live: 'بيانات مباشرة من المنصة',
      totalUsers: 'إجمالي المستخدمين',
      activeUsers: 'المستخدمون النشطون',
      profiles: 'الملفات الصحية',
      managedProfiles: 'الملفات المُدارة',
      appointmentsToday: 'مواعيد اليوم',
      monthlyAppointments: 'مواعيد هذا الشهر',
      pendingAppointments: 'المواعيد المعلقة',
      completedAppointments: 'المواعيد المكتملة',
      remindersToday: 'تذكيرات اليوم',
      documents: 'المستندات الطبية',
      aiConversations: 'محادثات الذكاء الاصطناعي',
      newRegistrations: 'التسجيلات الجديدة',
      monthlyGrowth: 'نمو شهري',
      userGrowth: 'نمو المستخدمين',
      appointmentVolume: 'حجم المواعيد',
      lastSixMonths: 'آخر ستة أشهر',
      genderDistribution: 'توزيع الملفات',
      recentUsers: 'أحدث التسجيلات',
      recentAppointments: 'أحدث المواعيد',
      viewUsers: 'عرض كل المستخدمين',
      patient: 'المريض',
      provider: 'مقدم الخدمة',
      date: 'التاريخ',
      status: 'الحالة',
      noData: 'لا يوجد نشاط متاح بعد.',
      retry: 'إعادة المحاولة',
      loadError: 'تعذر تحميل بيانات لوحة التحكم.',
      reviewStatsTitle: 'ملخص تقييمات التطبيق',
      reviewStatsAvg: 'متوسط التقييم',
      reviewStatsTotal: 'إجمالي التقييمات',
      totalAiRequests: 'إجمالي طلبات الذكاء الاصطناعي',
      flaggedAiRequests: 'طلبات مسيئة',
      aiUsage: 'نظرة عامة على استخدام الذكاء الاصطناعي',
      mostActiveUser: 'أكثر المستخدمين نشاطاً',
      usersNeedAttention: 'مستخدمون يحتاجون للمراجعة',
      reason: 'السبب',
      actionView: 'عرض المستخدم',
      reviewStatsVisible: 'مرئي',
      reviewStatsHidden: 'مخفي',
      reviewStatsViewAll: 'إدارة التقييمات'
    },
    reviews: {
      title: 'تقييمات التطبيق',
      subtitle: 'راقب الرضا وحلّل اتجاهات الملاحظات وأدر كل تقييم عبر دورة حياته الكاملة.',
      healthScore: 'مؤشر الصحة',
      healthScoreDesc: 'مؤشر الرضا المرجّح بالحداثة (0-100)',
      totalReviews: 'إجمالي التقييمات',
      pendingReviews: 'بانتظار المراجعة',
      positiveRate: 'نسبة الإيجابية',
      positiveRateDesc: '% من تقييمات 4-5 نجوم',
      thisWeek: 'هذا الأسبوع',
      withReply: 'مُردّ عليها',
      avgRating: 'متوسط التقييم',
      trendTitle: 'اتجاه التقييمات',
      trendDesc: 'متوسط التقييم الشهري خلال آخر 6 أشهر',
      categoryTitle: 'حسب الفئة',
      distTitle: 'توزيع النجوم',
      filterAll: 'الكل',
      filterPending: 'قيد الانتظار',
      filterReviewed: 'تمت مراجعته',
      filterResolved: 'تم حله',
      filterArchived: 'مؤرشف',
      sortNewest: 'الأحدث',
      sortOldest: 'الأقدم',
      sortStarsAsc: 'النجوم تصاعدي',
      sortStarsDesc: 'النجوم تنازلي',
      allCategories: 'كل الفئات',
      allStars: 'كل التقييمات',
      catGeneral: 'عام',
      catBugReport: 'تقرير خطأ',
      catFeatureRequest: 'طلب ميزة',
      catPerformance: 'الأداء',
      catUiUx: 'واجهة المستخدم',
      catContentQuality: 'جودة المحتوى',
      statusPending: 'قيد الانتظار',
      statusReviewed: 'تمت مراجعته',
      statusResolved: 'تم حله',
      statusArchived: 'مؤرشف',
      tableTitle: 'التقييمات',
      colUser: 'المستخدم',
      colStars: 'التقييم',
      colCategory: 'الفئة',
      colStatus: 'الحالة',
      colComment: 'التعليق',
      colDate: 'التاريخ',
      colActions: 'الإجراءات',
      detailTitle: 'تفاصيل التقييم',
      detailMeta: 'معلومات إضافية',
      detailDevice: 'الجهاز',
      detailVersion: 'الإصدار',
      detailLanguage: 'اللغة',
      adminNotes: 'ملاحظات داخلية',
      adminNotesPlaceholder: 'أضف ملاحظات خاصة لا يراها إلا المديرون...',
      saveNotes: 'حفظ الملاحظات',
      replyTitle: 'الرد على المستخدم',
      replyPlaceholder: 'اكتب ردًا سيُرسل كإشعار داخل التطبيق...',
      sendReply: 'إرسال الرد',
      updateReply: 'تحديث الرد',
      clearReply: 'مسح الرد',
      repliedAt: 'تم الرد',
      quickReplies: 'ردود سريعة',
      qr1: 'شكرًا على ملاحظاتك، لقد سجّلناها لفريقنا.',
      qr2: 'نحن نتعامل مع هذه المشكلة وسنُعلمك قريبًا.',
      qr3: 'هذه الميزة مدرجة في خارطة طريقنا، شكرًا على الاقتراح!',
      qr4: 'نأسف لهذه التجربة، فريقنا يعمل على إصلاحها.',
      visible: 'مرئي',
      hidden: 'مخفي',
      show: 'جعله عامًا',
      hide: 'إخفاء من العامة',
      delete: 'حذف',
      markReviewed: 'تمت المراجعة',
      markResolved: 'تم الحل',
      markArchived: 'أرشفة',
      markPending: 'إعادة لقيد الانتظار',
      viewDetail: 'فتح',
      closeDetail: 'إغلاق',
      noComment: 'لا يوجد تعليق',
      empty: 'لا توجد تقييمات تطابق الفلتر.',
      emptyAll: 'لا توجد تقييمات بعد.',
      loadError: 'تعذر تحميل التقييمات.',
      retry: 'إعادة المحاولة',
      saving: 'جارٍ الحفظ...',
      saved: 'تم الحفظ',
      deleteConfirm: 'حذف هذا التقييم نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.',
      cancel: 'إلغاء',
      confirm: 'حذف',
      previous: 'السابق',
      next: 'التالي',
      page: 'صفحة',
      of: 'من'
    },
    users: {
      title: 'إدارة المستخدمين',
      subtitle: 'ابحث وراجع وتحكم في صلاحية الدخول إلى حسابات رفيق.',
      total: 'مستخدم',
      search: 'بحث بالاسم أو البريد أو الهاتف',
      allStatuses: 'كل الحالات',
      active: 'نشط',
      inactive: 'غير نشط',
      allRoles: 'كل الأدوار',
      newest: 'الأحدث أولاً',
      oldest: 'الأقدم أولاً',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      account: 'الحساب',
      role: 'الدور',
      joined: 'تاريخ الانضمام',
      profile: 'الملف الصحي',
      actions: 'الإجراءات',
      available: 'متاح',
      missing: 'غير منشأ',
      activate: 'تفعيل',
      deactivate: 'إيقاف',
      activating: 'جارٍ التفعيل...',
      deactivating: 'جارٍ الإيقاف...',
      previous: 'السابق',
      next: 'التالي',
      page: 'صفحة',
      of: 'من',
      emptyTitle: 'لا يوجد مستخدمون مطابقون',
      emptyBody: 'جرّب مسح أحد الفلاتر أو استخدام عبارة بحث مختلفة.',
      loadError: 'تعذر تحميل المستخدمين.',
      updateError: 'تعذر تحديث حالة الحساب.',
      confirmDeactivate: 'هل تريد إيقاف هذا الحساب؟ سيفقد المستخدم إمكانية الدخول حتى إعادة تفعيله.',
      cancel: 'إلغاء',
      confirm: 'تأكيد الإيقاف'
    },
    auditLogs: {
      title: 'سجل التدقيق',
      subtitle: 'تتبع النشاطات الإدارية والتشغيلية الهامة عبر المنصة.',
      totalLogs:     'إجمالي السجلات',
      todayActivity: 'نشاطات اليوم',
      criticalEvents:'الأحداث الحرجة',
      adminActions:  'إجراءات المديرين',
      activitySummary: 'ملخص النشاط',
      infoEvents:    'معلوماتية',
      successEvents: 'ناجحة',
      warningEvents: 'تحذيرية',
      criticalCount: 'حرجة',
      searchPlaceholder: 'بحث في الإجراء أو المنفذ أو الهدف…',
      allModules:    'كل الوحدات',
      allSeverities: 'كل مستويات الخطورة',
      filterFrom:    'من تاريخ',
      filterTo:      'إلى تاريخ',
      clearFilters:  'مسح الفلاتر',
      colTime:       'الوقت',
      colActor:      'المنفذ',
      colModule:     'الوحدة',
      colAction:     'الإجراء',
      colTarget:     'الهدف',
      colSeverity:   'الخطورة',
      view:          'عرض',
      drawerTitle:       'تفاصيل النشاط',
      drawerTimestamp:   'الوقت',
      drawerActor:       'المنفذ',
      drawerModule:      'الوحدة',
      drawerTarget:      'الهدف',
      drawerSeverity:    'الخطورة',
      drawerDescription: 'الوصف',
      drawerChanges:     'التغييرات',
      drawerBefore:      'قبل',
      drawerAfter:       'بعد',
      drawerNoChanges:   'لم يتم تسجيل تغييرات للحقول في هذا الإجراء.',
      close:             'إغلاق',
      severityInfo:     'معلوماتي',
      severitySuccess:  'ناجح',
      severityWarning:  'تحذير',
      severityCritical: 'حرج',
      moduleUsers:   'المستخدمون',
      moduleReviews: 'تقييمات التطبيق',
      moduleAiOps:   'عمليات الذكاء الاصطناعي',
      moduleSettings:'الإعدادات',
      moduleSystem:  'النظام',
      empty:    'لا توجد سجلات نشاط تطابق الفلتر.',
      emptyAll: 'لم يتم تسجيل أي نشاط بعد.',
      loadError:'تعذر تحميل سجلات النشاط.',
      retry:    'إعادة المحاولة',
      previous: 'السابق',
      next:     'التالي',
      page:     'صفحة',
      of:       'من',
      actionUserActivated:   'تفعيل مستخدم',
      actionUserSuspended:   'إيقاف مستخدم',
      actionRoleChanged:     'تغيير الدور',
      actionFeedbackReviewed:'مراجعة ملاحظة',
      actionFeedbackResolved:'حل ملاحظة',
      actionReviewHidden:    'إخفاء تقييم',
      actionReviewPublished: 'نشر تقييم',
      actionMaintenanceEnabled: 'تفعيل وضع الصيانة',
      actionConfigChanged:   'تغيير الإعدادات',
    },
    placeholder: {
      title: 'أساس الوحدة جاهز',
      body: 'هذه الوجهة متصلة بمساحة الإدارة المحمية وجاهزة لواجهات API وسير العمل الخاص بها في مرحلة التنفيذ التالية.',
      back: 'العودة إلى لوحة التحكم'
    },
    aiOps: {
      title: 'عمليات الذكاء الاصطناعي',
      subtitle: 'مراقبة جودة الذكاء الاصطناعي وتقييمه وتحسينه المستمر.',
      tabOverview: 'نظرة عامة',
      tabConversations: 'المحادثات',
      tabFeedback: 'التقييمات',
      tabPerformance: 'الأداء',

      healthScore: 'مؤشر صحة الذكاء الاصطناعي',
      healthGood: 'سليم',
      healthFair: 'يحتاج انتباهاً',
      healthPoor: 'متدهور',
      healthScoreFormula: 'المؤشر = (معدل النجاح 7 أيام × 65%) + (التقييم الإيجابي × 35%)',
      healthScoreDesc: 'مؤشر جودة مركّب. 85 أو أعلى يعني صحة جيدة، 70–84 يحتاج انتباهاً، أقل من 70 متدهور.',
      positiveRate: 'معدل التقييم الإيجابي',
      unreviewedNegative: 'سلبي غير مراجع',
      failedLast7d: 'فشل (7 أيام)',
      avgResponseTime: 'متوسط وقت الاستجابة',
      requestsToday: 'طلبات اليوم',
      chatConversations: 'محادثات الدردشة',
      voiceSessions: 'جلسات الصوت',
      qualityTrend: 'مؤشر الجودة',
      last7Days: 'آخر 7 أيام',
      requests: 'الطلبات',
      failures: 'الأخطاء',
      thumbsUpShort: '👍',
      thumbsDownShort: '👎',

      insights: 'رؤى الذكاء الاصطناعي',
      insightsSub: 'نتائج رئيسية من آخر 30 يوماً',
      mostUsedFeature: 'الميزة الأكثر استخداماً',
      mostReportedCategory: 'المشكلة الأكثر إبلاغاً',
      highestErrorFeature: 'أعلى مصدر للأخطاء',
      slowestFeature: 'الميزة الأبطأ',
      fastestFeature: 'الميزة الأسرع',
      insightRequests: 'طلب',
      insightErrors: 'خطأ',
      insightAvgMs: 'متوسط',
      insightOccurrences: 'تكرار',
      noInsights: 'لا توجد بيانات كافية بعد.',

      incidents: 'الحوادث النشطة',
      incidentsSub: 'تنبيهات تلقائية بناءً على المقاييس الحالية',
      incidentHighError: 'معدل خطأ مرتفع',
      incidentHighErrorDesc: 'أكثر من 20 طلباً فاشلاً في آخر 7 أيام.',
      incidentLowRating: 'تقييم إيجابي منخفض',
      incidentLowRatingDesc: 'رضا المستخدمين أقل من 60%. راجع التقييمات السلبية فوراً.',
      incidentPendingReviews: 'تقييمات سلبية غير مراجعة',
      incidentPendingReviewsDesc: 'أكثر من 10 عناصر سلبية تنتظر مراجعة المدير.',
      incidentSlowResponse: 'وقت استجابة مرتفع',
      incidentSlowResponseDesc: 'متوسط وقت استجابة الذكاء الاصطناعي يتجاوز 10 ثوانٍ.',
      noIncidents: 'لا توجد حوادث نشطة — الذكاء الاصطناعي يعمل بشكل طبيعي.',
      severityCritical: 'حرج',
      severityWarning: 'تحذير',

      user: 'المستخدم',
      feature: 'الميزة',
      model: 'النموذج',
      duration: 'المدة',
      status: 'الحالة',
      date: 'التاريخ',
      success: 'ناجح',
      failed: 'فشل',
      searchPlaceholder: 'بحث بالمستخدم أو الميزة…',
      allFeatures: 'كل الميزات',
      allStatuses: 'كل الحالات',
      noRequests: 'لا توجد طلبات ذكاء اصطناعي مسجلة بعد.',
      noRequestsSub: 'تتراكم البيانات فور استخدام ميزات الذكاء الاصطناعي.',
      requestDetail: 'تفاصيل الطلب',
      close: 'إغلاق',
      userPrompt: 'رسالة المستخدم',
      aiResponse: 'رد الذكاء الاصطناعي',
      errorInfo: 'معلومات الخطأ',
      noConversation: 'لا توجد محادثة مرتبطة بهذا الطلب.',
      requestMeta: 'بيانات الطلب',
      clickRowHint: 'انقر على أي صف لفحص تفاصيل الطلب.',

      allReactions: 'كل التفاعلات',
      positive: 'إيجابي',
      negative: 'سلبي',
      allTriageStatuses: 'كل الحالات',
      statusNew: 'جديد',
      statusInvestigating: 'قيد التحقيق',
      statusResolved: 'محلول',
      statusIgnored: 'تجاهل',
      allCategories: 'كل الفئات',
      catHallucination: 'هلوسة',
      catWrongMedical: 'نصيحة طبية خاطئة',
      catOcrIssue: 'خطأ في قراءة المستندات',
      catVoice: 'التعرف على الصوت',
      catPerformance: 'الأداء',
      catBug: 'خلل برمجي',
      catFeatureRequest: 'طلب ميزة',
      catOther: 'أخرى',
      dateFrom: 'من',
      dateTo: 'إلى',
      reaction: 'التفاعل',
      uncategorized: 'غير مصنف',
      expand: 'توسيع',
      collapse: 'طي',
      userQuestion: 'سؤال المستخدم',
      noUserQuestion: 'سؤال المستخدم غير متاح.',
      aiMessage: 'رسالة الذكاء الاصطناعي',
      userComment: 'تعليق المستخدم',
      noComment: 'لم يتم إضافة تعليق.',
      adminReview: 'مراجعة المدير',
      category: 'الفئة',
      triageStatus: 'حالة المراجعة',
      adminNotes: 'ملاحظات داخلية',
      adminNotesPlaceholder: 'ملاحظات داخلية للمراجعة (غير مرئية للمستخدمين)…',
      saveReview: 'حفظ المراجعة',
      saving: 'جارٍ الحفظ…',
      feedbackContextHeader: 'سياق المحادثة الكامل — راجع سؤال المستخدم وردّ الذكاء الاصطناعي معاً لتقييم الجودة.',
      noFeedback: 'لا توجد تقييمات مسجلة بعد.',
      noFeedbackSub: 'تظهر التقييمات عندما يُقيّم المستخدمون ردود الذكاء الاصطناعي.',

      dailyRequests: 'حجم الطلبات اليومية',
      errorRate: 'معدل الخطأ',
      errorRateDesc: 'نسبة الطلبات التي أرجعت خطأ.',
      slowRequests: 'الطلبات البطيئة (>5 ث)',
      slowRequestsDesc: 'الطلبات التي استغرقت أكثر من 5 ثوانٍ.',
      p95Latency: 'زمن الاستجابة P95',
      p95LatencyDesc: '95% من الطلبات اكتملت خلال هذا الوقت. ارتفاعه يعني وجود طلبات بطيئة متقطعة.',
      avgLatency: 'متوسط زمن الاستجابة',
      avgLatencyDesc: 'متوسط زمن استجابة الذكاء الاصطناعي في الفترة المحددة.',
      requestsByFeature: 'الطلبات حسب الميزة',
      last30Days: 'آخر 30 يوماً',
      noPerformanceData: 'لا توجد بيانات أداء بعد.',

      // ── Usage Intelligence ─────────────────────────────────────────────
      tabUsageIntelligence: 'ذكاء الاستخدام',
      uiTitle: 'ذكاء الاستخدام',
      uiSubtitle: 'مراقبة استهلاك موارد الذكاء الاصطناعي وتحديد أنماط الاستخدام غير المعتادة.',
      uiTotalRequests: 'إجمالي طلبات الذكاء الاصطناعي',
      uiFlaggedRequests: 'الطلبات المُبلَّغ عنها',
      uiUsersToReview: 'مستخدمون يحتاجون مراجعة',
      uiWarningsSent: 'تحذيرات صادرة',
      uiAttentionQueue: 'قائمة الانتباه',
      uiAttentionQueueSub: 'مستخدمون لديهم طلبات مُبلَّغ عنها، مرتبة حسب الأولوية',
      uiColUser: 'المستخدم',
      uiColTotalReq: 'إجمالي الطلبات',
      uiColFlagged: 'المُبلَّغ عنها',
      uiColWarnings: 'التحذيرات',
      uiColLastActivity: 'آخر نشاط',
      uiColActions: 'الإجراءات',
      uiViewDetail: 'مراجعة',
      uiEmptyQueue: 'لا يوجد مستخدمون بطلبات مُبلَّغ عنها.',
      uiEmptyQueueSub: 'قائمة الانتباه فارغة — استخدام الذكاء الاصطناعي يبدو طبيعياً.',
      uiUserDetail: 'تفاصيل نشاط المستخدم',
      uiUserDetailSub: 'الطلبات التي صنّفها الذكاء الاصطناعي كإشكالية',
      uiColRequestType: 'نوع الطلب',
      uiColUserRequest: 'طلب المستخدم',
      uiColAiResponse: 'رد الذكاء الاصطناعي',
      uiColClassification: 'التصنيف',
      uiColReason: 'السبب',
      uiColDate: 'التاريخ',
      uiNoFlagged: 'لا توجد طلبات مُبلَّغ عنها لهذا المستخدم.',
      uiActionHistory: 'سجل إجراءات المدير',
      uiNoActions: 'لم يتم اتخاذ أي إجراء بعد.',
      uiColAction: 'الإجراء',
      uiColAdmin: 'المدير',
      uiColNotes: 'ملاحظات',
      uiSendWarning: 'إرسال تحذير',
      uiSendFinalWarning: 'إرسال تحذير نهائي',
      uiRestrictAi: 'تقييد الوصول للذكاء الاصطناعي',
      uiRemoveAiRestriction: 'رفع تقييد الذكاء الاصطناعي',
      uiRestrictAccount: 'تقييد الحساب',
      uiRemoveAccountRestriction: 'رفع تقييد الحساب',
      uiSuspendAccount: 'تعليق الحساب',
      uiUnsuspendAccount: 'رفع تعليق الحساب',
      uiActionNotes: 'ملاحظات (اختياري)',
      uiActionNotesPlaceholder: 'أضف سبباً أو ملاحظة لهذا الإجراء...',
      uiConfirmAction: 'تأكيد',
      uiCancelAction: 'إلغاء',
      uiActionSending: 'جارٍ الإرسال...',
      uiActionSuccess: 'تم تنفيذ الإجراء بنجاح.',
      uiActionError: 'تعذر تنفيذ الإجراء.',
      uiBack: 'العودة للقائمة',
      uiStatusAiRestricted: 'مقيد الذكاء الاصطناعي',
      uiStatusRestricted: 'الحساب مقيد',
      uiStatusSuspended: 'موقوف',
      uiClassNonMedical: 'ملف غير طبي',
      uiClassWrongType: 'نوع مستند خاطئ',
      uiClassOffDomainChat: 'محادثة خارج النطاق',
      uiClassOffDomainVoice: 'صوت خارج النطاق',
      uiClassPolicyViolation: 'مخالفة السياسة',
      uiActionWarning: 'تحذير',
      uiActionFinalWarning: 'تحذير نهائي',
      uiActionRestrictAi: 'تم تقييد الذكاء الاصطناعي',
      uiActionRemoveAiRestriction: 'تم رفع تقييد الذكاء الاصطناعي',
      uiActionRestrictAccount: 'تم تقييد الحساب',
      uiActionRemoveAccountRestriction: 'تم رفع تقييد الحساب',
      uiActionSuspend: 'تم تعليق الحساب',
      uiActionUnsuspend: 'تم رفع التعليق',
      uiLoadingUser: 'جارٍ تحميل بيانات المستخدم...',

      loadError: 'تعذر تحميل البيانات.',
      retry: 'إعادة المحاولة',
      previous: 'السابق',
      next: 'التالي',
      page: 'صفحة',
      of: 'من',
      ms: 'مللي ث',
      pct: '%'
    }
  }
} as const;
