export const adminCopy = {
  en: {
    brand: 'Rafiq Control',
    workspace: 'Administration',
    search: 'Search the admin portal...',
    menu: 'Open navigation',
    close: 'Close navigation',
    notifications: 'Notifications',
    language: 'Switch to Arabic',
    theme: 'Toggle dark mode',
    logout: 'Logout',
    profile: 'Admin profile',
    nav: {
      dashboard: 'Dashboard',
      users: 'Users',
      families: 'Families',
      aiOperations: 'AI Operations',
      medicalRecords: 'Medical Records',
      medications: 'Medications',
      appointments: 'Appointments',
      documents: 'Documents',
      analytics: 'Analytics',
      settings: 'System Settings',
      auditLogs: 'Audit Logs'
    },
    dashboard: {
      title: 'System overview',
      subtitle: 'Monitor adoption, care activity, and platform health from one place.',
      live: 'Live platform data',
      totalUsers: 'Total users',
      activeUsers: 'Active users',
      profiles: 'Health profiles',
      managedProfiles: 'Managed profiles',
      appointmentsToday: 'Appointments today',
      monthlyAppointments: 'Appointments this month',
      pendingAppointments: 'Pending appointments',
      completedAppointments: 'Completed appointments',
      remindersToday: 'Reminders today',
      documents: 'Medical documents',
      aiConversations: 'AI conversations',
      newRegistrations: 'New registrations',
      monthlyGrowth: 'monthly growth',
      userGrowth: 'User growth',
      appointmentVolume: 'Appointment volume',
      lastSixMonths: 'Last six months',
      genderDistribution: 'Profile distribution',
      recentUsers: 'Recent registrations',
      recentAppointments: 'Recent appointments',
      viewUsers: 'View all users',
      patient: 'Patient',
      provider: 'Provider',
      date: 'Date',
      status: 'Status',
      noData: 'No activity is available yet.',
      retry: 'Retry',
      loadError: 'Dashboard data could not be loaded.'
    },
    users: {
      title: 'User management',
      subtitle: 'Search, review, and control access to Rafiq accounts.',
      total: 'users',
      search: 'Search by name, email, or phone',
      allStatuses: 'All statuses',
      active: 'Active',
      inactive: 'Inactive',
      allRoles: 'All roles',
      newest: 'Newest first',
      oldest: 'Oldest first',
      name: 'Name',
      email: 'Email',
      account: 'Account',
      role: 'Role',
      joined: 'Joined',
      profile: 'Health profile',
      actions: 'Actions',
      available: 'Available',
      missing: 'Not created',
      activate: 'Activate',
      deactivate: 'Deactivate',
      activating: 'Activating...',
      deactivating: 'Deactivating...',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
      emptyTitle: 'No users match these filters',
      emptyBody: 'Try clearing a filter or using a different search term.',
      loadError: 'Users could not be loaded.',
      updateError: 'The account status could not be updated.',
      confirmDeactivate: 'Deactivate this account? The user will lose access until it is reactivated.',
      cancel: 'Cancel',
      confirm: 'Confirm deactivation'
    },
    placeholder: {
      title: 'Module foundation ready',
      body: 'This destination is connected to the protected admin workspace and is ready for its dedicated API and workflow in the next implementation phase.',
      back: 'Back to dashboard'
    },
    aiOps: {
      title: 'AI Operations',
      subtitle: 'Continuously monitor, evaluate, and improve AI quality and reliability.',
      tabOverview: 'Overview',
      tabConversations: 'Conversations',
      tabFeedback: 'Feedback',
      tabPerformance: 'Performance',

      // ── Overview ──────────────────────────────────────────────────────
      healthScore: 'AI Health Score',
      healthGood: 'Healthy',
      healthFair: 'Needs attention',
      healthPoor: 'Degraded',
      healthScoreFormula: 'Score = (7-day Success Rate × 65%) + (Positive Rating × 35%)',
      healthScoreDesc: 'Composite quality signal. A score of 85+ is healthy, 70–84 needs attention, below 70 is degraded.',
      positiveRate: 'Positive rating',
      unreviewedNegative: 'Unreviewed negative',
      failedLast7d: 'Failed (7 days)',
      avgResponseTime: 'Avg response time',
      requestsToday: 'Requests today',
      chatConversations: 'Chat conversations',
      voiceSessions: 'Voice sessions',
      qualityTrend: 'Quality trend',
      last7Days: 'Last 7 days',
      requests: 'Requests',
      failures: 'Failures',
      thumbsUpShort: '👍',
      thumbsDownShort: '👎',

      // ── Insights ──────────────────────────────────────────────────────
      insights: 'AI Insights',
      insightsSub: 'Key findings from the last 30 days',
      mostUsedFeature: 'Most Used Feature',
      mostReportedCategory: 'Most Reported Issue',
      highestErrorFeature: 'Highest Error Source',
      slowestFeature: 'Slowest Feature',
      fastestFeature: 'Fastest Feature',
      insightRequests: 'requests',
      insightErrors: 'errors',
      insightAvgMs: 'avg',
      insightOccurrences: 'occurrences',
      noInsights: 'Not enough data yet.',

      // ── Incidents ─────────────────────────────────────────────────────
      incidents: 'Active Incidents',
      incidentsSub: 'Automated alerts based on current metrics',
      incidentHighError: 'High failure rate',
      incidentHighErrorDesc: 'More than 20 failed requests in the last 7 days.',
      incidentLowRating: 'Low positive rating',
      incidentLowRatingDesc: 'User satisfaction is below 60%. Review negative feedback immediately.',
      incidentPendingReviews: 'Unreviewed negative feedback',
      incidentPendingReviewsDesc: 'More than 10 negative items are waiting for admin review.',
      incidentSlowResponse: 'High average response time',
      incidentSlowResponseDesc: 'Average AI response time exceeds 10 seconds.',
      noIncidents: 'No active incidents — AI is operating normally.',
      severityCritical: 'Critical',
      severityWarning: 'Warning',

      // ── Conversations ──────────────────────────────────────────────────
      user: 'User',
      feature: 'Feature',
      model: 'Model',
      duration: 'Duration',
      status: 'Status',
      date: 'Date',
      success: 'Success',
      failed: 'Failed',
      searchPlaceholder: 'Search by user or feature…',
      allFeatures: 'All features',
      allStatuses: 'All statuses',
      noRequests: 'No AI requests recorded yet.',
      noRequestsSub: 'Telemetry accrues once users start using AI features.',
      // Drawer
      requestDetail: 'Request detail',
      close: 'Close',
      userPrompt: 'User prompt',
      aiResponse: 'AI response',
      errorInfo: 'Error information',
      noConversation: 'No conversation linked to this request.',
      requestMeta: 'Request metadata',
      clickRowHint: 'Click any row to inspect the request.',

      // ── Feedback ──────────────────────────────────────────────────────
      allReactions: 'All reactions',
      positive: 'Positive',
      negative: 'Negative',
      allTriageStatuses: 'All statuses',
      statusNew: 'New',
      statusInvestigating: 'Investigating',
      statusResolved: 'Resolved',
      statusIgnored: 'Ignored',
      allCategories: 'All categories',
      catHallucination: 'Hallucination',
      catWrongMedical: 'Wrong Medical Advice',
      catOcrIssue: 'OCR Issue',
      catVoice: 'Voice Recognition',
      catPerformance: 'Performance',
      catBug: 'Bug',
      catFeatureRequest: 'Feature Request',
      catOther: 'Other',
      dateFrom: 'From',
      dateTo: 'To',
      // Compact row
      reaction: 'Reaction',
      uncategorized: 'Uncategorized',
      expand: 'Expand',
      collapse: 'Collapse',
      // Expanded panel
      userQuestion: 'User question',
      noUserQuestion: 'User question not available.',
      aiMessage: 'AI message',
      userComment: 'User comment',
      noComment: 'No comment provided.',
      adminReview: 'Admin review',
      category: 'Category',
      triageStatus: 'Review status',
      adminNotes: 'Internal notes',
      adminNotesPlaceholder: 'Internal notes for this review (not visible to users)…',
      saveReview: 'Save review',
      saving: 'Saving…',
      feedbackContextHeader: 'Full conversation context — review the user question and AI response together to assess quality.',
      noFeedback: 'No feedback recorded yet.',
      noFeedbackSub: 'Feedback appears here when users rate AI responses.',

      // ── Performance ───────────────────────────────────────────────────
      dailyRequests: 'Daily request volume',
      errorRate: 'Error rate',
      errorRateDesc: 'Percentage of requests that returned an error.',
      slowRequests: 'Slow requests (>5 s)',
      slowRequestsDesc: 'Requests that took longer than 5 seconds to complete.',
      p95Latency: 'P95 latency',
      p95LatencyDesc: '95% of requests completed within this response time. A high P95 indicates occasional slow outliers.',
      avgLatency: 'Avg latency',
      avgLatencyDesc: 'Mean response time across all AI requests in the selected period.',
      requestsByFeature: 'Requests by feature',
      last30Days: 'Last 30 days',
      noPerformanceData: 'No performance data yet.',

      // ── Common ─────────────────────────────────────────────────────────
      loadError: 'Data could not be loaded.',
      retry: 'Retry',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
      ms: 'ms',
      pct: '%'
    }
  },
  ar: {
    brand: 'إدارة رفيق',
    workspace: 'لوحة الإدارة',
    search: 'ابحث في لوحة الإدارة...',
    menu: 'فتح القائمة',
    close: 'إغلاق القائمة',
    notifications: 'الإشعارات',
    language: 'التبديل إلى الإنجليزية',
    theme: 'تبديل الوضع الداكن',
    logout: 'تسجيل الخروج',
    profile: 'ملف المدير',
    nav: {
      dashboard: 'لوحة التحكم',
      users: 'المستخدمون',
      families: 'العائلات',
      aiOperations: 'عمليات الذكاء الاصطناعي',
      medicalRecords: 'السجلات الطبية',
      medications: 'الأدوية',
      appointments: 'المواعيد',
      documents: 'المستندات',
      analytics: 'الإحصائيات',
      settings: 'إعدادات النظام',
      auditLogs: 'سجل التدقيق'
    },
    dashboard: {
      title: 'نظرة عامة على النظام',
      subtitle: 'تابع الاستخدام ونشاط الرعاية وصحة المنصة من مكان واحد.',
      live: 'بيانات مباشرة من المنصة',
      totalUsers: 'إجمالي المستخدمين',
      activeUsers: 'المستخدمون النشطون',
      profiles: 'الملفات الصحية',
      managedProfiles: 'الملفات المُدارة',
      appointmentsToday: 'مواعيد اليوم',
      monthlyAppointments: 'مواعيد هذا الشهر',
      pendingAppointments: 'المواعيد المعلقة',
      completedAppointments: 'المواعيد المكتملة',
      remindersToday: 'تذكيرات اليوم',
      documents: 'المستندات الطبية',
      aiConversations: 'محادثات الذكاء الاصطناعي',
      newRegistrations: 'التسجيلات الجديدة',
      monthlyGrowth: 'نمو شهري',
      userGrowth: 'نمو المستخدمين',
      appointmentVolume: 'حجم المواعيد',
      lastSixMonths: 'آخر ستة أشهر',
      genderDistribution: 'توزيع الملفات',
      recentUsers: 'أحدث التسجيلات',
      recentAppointments: 'أحدث المواعيد',
      viewUsers: 'عرض كل المستخدمين',
      patient: 'المريض',
      provider: 'مقدم الخدمة',
      date: 'التاريخ',
      status: 'الحالة',
      noData: 'لا يوجد نشاط متاح بعد.',
      retry: 'إعادة المحاولة',
      loadError: 'تعذر تحميل بيانات لوحة التحكم.'
    },
    users: {
      title: 'إدارة المستخدمين',
      subtitle: 'ابحث وراجع وتحكم في صلاحية الدخول إلى حسابات رفيق.',
      total: 'مستخدم',
      search: 'بحث بالاسم أو البريد أو الهاتف',
      allStatuses: 'كل الحالات',
      active: 'نشط',
      inactive: 'غير نشط',
      allRoles: 'كل الأدوار',
      newest: 'الأحدث أولاً',
      oldest: 'الأقدم أولاً',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      account: 'الحساب',
      role: 'الدور',
      joined: 'تاريخ الانضمام',
      profile: 'الملف الصحي',
      actions: 'الإجراءات',
      available: 'متاح',
      missing: 'غير منشأ',
      activate: 'تفعيل',
      deactivate: 'إيقاف',
      activating: 'جارٍ التفعيل...',
      deactivating: 'جارٍ الإيقاف...',
      previous: 'السابق',
      next: 'التالي',
      page: 'صفحة',
      of: 'من',
      emptyTitle: 'لا يوجد مستخدمون مطابقون',
      emptyBody: 'جرّب مسح أحد الفلاتر أو استخدام عبارة بحث مختلفة.',
      loadError: 'تعذر تحميل المستخدمين.',
      updateError: 'تعذر تحديث حالة الحساب.',
      confirmDeactivate: 'هل تريد إيقاف هذا الحساب؟ سيفقد المستخدم إمكانية الدخول حتى إعادة تفعيله.',
      cancel: 'إلغاء',
      confirm: 'تأكيد الإيقاف'
    },
    placeholder: {
      title: 'أساس الوحدة جاهز',
      body: 'هذه الوجهة متصلة بمساحة الإدارة المحمية وجاهزة لواجهات API وسير العمل الخاص بها في مرحلة التنفيذ التالية.',
      back: 'العودة إلى لوحة التحكم'
    },
    aiOps: {
      title: 'عمليات الذكاء الاصطناعي',
      subtitle: 'مراقبة جودة الذكاء الاصطناعي وتقييمه وتحسينه المستمر.',
      tabOverview: 'نظرة عامة',
      tabConversations: 'المحادثات',
      tabFeedback: 'التقييمات',
      tabPerformance: 'الأداء',

      healthScore: 'مؤشر صحة الذكاء الاصطناعي',
      healthGood: 'سليم',
      healthFair: 'يحتاج انتباهاً',
      healthPoor: 'متدهور',
      healthScoreFormula: 'المؤشر = (معدل النجاح 7 أيام × 65%) + (التقييم الإيجابي × 35%)',
      healthScoreDesc: 'مؤشر جودة مركّب. 85 أو أعلى يعني صحة جيدة، 70–84 يحتاج انتباهاً، أقل من 70 متدهور.',
      positiveRate: 'معدل التقييم الإيجابي',
      unreviewedNegative: 'سلبي غير مراجع',
      failedLast7d: 'فشل (7 أيام)',
      avgResponseTime: 'متوسط وقت الاستجابة',
      requestsToday: 'طلبات اليوم',
      chatConversations: 'محادثات الدردشة',
      voiceSessions: 'جلسات الصوت',
      qualityTrend: 'مؤشر الجودة',
      last7Days: 'آخر 7 أيام',
      requests: 'الطلبات',
      failures: 'الأخطاء',
      thumbsUpShort: '👍',
      thumbsDownShort: '👎',

      insights: 'رؤى الذكاء الاصطناعي',
      insightsSub: 'نتائج رئيسية من آخر 30 يوماً',
      mostUsedFeature: 'الميزة الأكثر استخداماً',
      mostReportedCategory: 'المشكلة الأكثر إبلاغاً',
      highestErrorFeature: 'أعلى مصدر للأخطاء',
      slowestFeature: 'الميزة الأبطأ',
      fastestFeature: 'الميزة الأسرع',
      insightRequests: 'طلب',
      insightErrors: 'خطأ',
      insightAvgMs: 'متوسط',
      insightOccurrences: 'تكرار',
      noInsights: 'لا توجد بيانات كافية بعد.',

      incidents: 'الحوادث النشطة',
      incidentsSub: 'تنبيهات تلقائية بناءً على المقاييس الحالية',
      incidentHighError: 'معدل خطأ مرتفع',
      incidentHighErrorDesc: 'أكثر من 20 طلباً فاشلاً في آخر 7 أيام.',
      incidentLowRating: 'تقييم إيجابي منخفض',
      incidentLowRatingDesc: 'رضا المستخدمين أقل من 60%. راجع التقييمات السلبية فوراً.',
      incidentPendingReviews: 'تقييمات سلبية غير مراجعة',
      incidentPendingReviewsDesc: 'أكثر من 10 عناصر سلبية تنتظر مراجعة المدير.',
      incidentSlowResponse: 'وقت استجابة مرتفع',
      incidentSlowResponseDesc: 'متوسط وقت استجابة الذكاء الاصطناعي يتجاوز 10 ثوانٍ.',
      noIncidents: 'لا توجد حوادث نشطة — الذكاء الاصطناعي يعمل بشكل طبيعي.',
      severityCritical: 'حرج',
      severityWarning: 'تحذير',

      user: 'المستخدم',
      feature: 'الميزة',
      model: 'النموذج',
      duration: 'المدة',
      status: 'الحالة',
      date: 'التاريخ',
      success: 'ناجح',
      failed: 'فشل',
      searchPlaceholder: 'بحث بالمستخدم أو الميزة…',
      allFeatures: 'كل الميزات',
      allStatuses: 'كل الحالات',
      noRequests: 'لا توجد طلبات ذكاء اصطناعي مسجلة بعد.',
      noRequestsSub: 'تتراكم البيانات فور استخدام ميزات الذكاء الاصطناعي.',
      requestDetail: 'تفاصيل الطلب',
      close: 'إغلاق',
      userPrompt: 'رسالة المستخدم',
      aiResponse: 'رد الذكاء الاصطناعي',
      errorInfo: 'معلومات الخطأ',
      noConversation: 'لا توجد محادثة مرتبطة بهذا الطلب.',
      requestMeta: 'بيانات الطلب',
      clickRowHint: 'انقر على أي صف لفحص تفاصيل الطلب.',

      allReactions: 'كل التفاعلات',
      positive: 'إيجابي',
      negative: 'سلبي',
      allTriageStatuses: 'كل الحالات',
      statusNew: 'جديد',
      statusInvestigating: 'قيد التحقيق',
      statusResolved: 'محلول',
      statusIgnored: 'تجاهل',
      allCategories: 'كل الفئات',
      catHallucination: 'هلوسة',
      catWrongMedical: 'نصيحة طبية خاطئة',
      catOcrIssue: 'خطأ في قراءة المستندات',
      catVoice: 'التعرف على الصوت',
      catPerformance: 'الأداء',
      catBug: 'خلل برمجي',
      catFeatureRequest: 'طلب ميزة',
      catOther: 'أخرى',
      dateFrom: 'من',
      dateTo: 'إلى',
      reaction: 'التفاعل',
      uncategorized: 'غير مصنف',
      expand: 'توسيع',
      collapse: 'طي',
      userQuestion: 'سؤال المستخدم',
      noUserQuestion: 'سؤال المستخدم غير متاح.',
      aiMessage: 'رسالة الذكاء الاصطناعي',
      userComment: 'تعليق المستخدم',
      noComment: 'لم يتم إضافة تعليق.',
      adminReview: 'مراجعة المدير',
      category: 'الفئة',
      triageStatus: 'حالة المراجعة',
      adminNotes: 'ملاحظات داخلية',
      adminNotesPlaceholder: 'ملاحظات داخلية للمراجعة (غير مرئية للمستخدمين)…',
      saveReview: 'حفظ المراجعة',
      saving: 'جارٍ الحفظ…',
      feedbackContextHeader: 'سياق المحادثة الكامل — راجع سؤال المستخدم وردّ الذكاء الاصطناعي معاً لتقييم الجودة.',
      noFeedback: 'لا توجد تقييمات مسجلة بعد.',
      noFeedbackSub: 'تظهر التقييمات عندما يُقيّم المستخدمون ردود الذكاء الاصطناعي.',

      dailyRequests: 'حجم الطلبات اليومية',
      errorRate: 'معدل الخطأ',
      errorRateDesc: 'نسبة الطلبات التي أرجعت خطأ.',
      slowRequests: 'الطلبات البطيئة (>5 ث)',
      slowRequestsDesc: 'الطلبات التي استغرقت أكثر من 5 ثوانٍ.',
      p95Latency: 'زمن الاستجابة P95',
      p95LatencyDesc: '95% من الطلبات اكتملت خلال هذا الوقت. ارتفاعه يعني وجود طلبات بطيئة متقطعة.',
      avgLatency: 'متوسط زمن الاستجابة',
      avgLatencyDesc: 'متوسط زمن استجابة الذكاء الاصطناعي في الفترة المحددة.',
      requestsByFeature: 'الطلبات حسب الميزة',
      last30Days: 'آخر 30 يوماً',
      noPerformanceData: 'لا توجد بيانات أداء بعد.',

      loadError: 'تعذر تحميل البيانات.',
      retry: 'إعادة المحاولة',
      previous: 'السابق',
      next: 'التالي',
      page: 'صفحة',
      of: 'من',
      ms: 'مللي ث',
      pct: '%'
    }
  }
} as const;
