<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Rafiq.API</RootNamespace>
    <UserSecretsId>848b2a12-dc2f-4a17-a9f5-354fc58d408c</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>

    <PackageReference Include="Hangfire.AspNetCore" Version="1.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="9.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rafiq.Application\Rafiq.Application.csproj" />
    <ProjectReference Include="..\Rafiq.Infrastructure\Rafiq.Infrastructure.csproj" />
  </ItemGroup>
</Project>
