/**
 * @file assistant-command.ts
 * @description Defines the command structures, command types, and command execution results for the Rafiq AI Agent architecture.
 * Responsibility: Provide data models for commands issued by the user or generated by AI workflows.
 */

export type CommandType =
  | 'navigate'
  | 'highlight'
  | 'showDialog'
  | 'callApi'
  | 'startTour'
  | 'custom';

export interface AssistantCommand<T = any> {
  id: string;
  type: CommandType;
  toolName: string;
  payload: T;
  timestamp: number;
}

export interface CommandResult<T = any> {
  commandId: string;
  success: boolean;
  data?: T;
  error?: string;
  executionTimeMs: number;
}
