import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Injectable({
  providedIn: 'root',
})
export class PdfService {
  download(record: any): void {

    switch (record.type) {

      case 'lab':
        this.generateLabPdf(record);
        break;

      case 'imaging':
        this.generateImagingPdf(record)
        break;

      case 'prescription':
        this.generatePrescriptionPdf(record)
        break;

      case 'medicine':
        this.generateMedicineBoxPdf(record);
        break;
    }
  }

private async addHeader(doc: jsPDF, title: string): Promise<number> {

    const logo = await this.loadLogo();

    const pageWidth = doc.internal.pageSize.getWidth();

    const logoWidth = 20;
    const logoHeight = 20;

    doc.addImage(
        logo,
        'PNG',
        (pageWidth - logoWidth) / 2,
        10,
        logoWidth,
        logoHeight
    );

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);

    doc.text('Rafiq AI', pageWidth / 2, 38, {
        align: 'center'
    });

    doc.setFontSize(16);

    doc.text(title, pageWidth / 2, 50, {
        align: 'center'
    });

    doc.setDrawColor(220);

    doc.line(20, 58, pageWidth - 20, 58);

    return 72;
}

private addSummary(
    doc: jsPDF,
    summary: string,
    y: number
): number {

    doc.setFontSize(14);

    doc.text("AI Summary",15,y);

    y += 8;

    doc.setFontSize(11);

    const lines = doc.splitTextToSize(summary,180);

    doc.text(lines,15,y);

    return y + lines.length * 6 + 10;
}

private addFooter(doc: jsPDF){

    const pageHeight = doc.internal.pageSize.getHeight();

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
        "Generated by Rafiq AI",
        15,
        pageHeight - 10
    );

}
  
  private async loadLogo(): Promise<string> {

    const response = await fetch('/images/RafiqLogo.png');

    const blob = await response.blob();

    return new Promise((resolve) => {

      const reader = new FileReader();

      reader.onloadend = () => resolve(reader.result as string);

      reader.readAsDataURL(blob);



    });

  }
private async generateLabPdf(record:any){

    const doc = new jsPDF();

    let y = await this.addHeader(
        doc,
        "Laboratory Report"
    );

    doc.setFontSize(12);

    doc.text(`Lab Name: ${record.rawRecord.labName}`,15,y);

    y += 8;

    doc.text(`Doctor: ${record.rawRecord.doctorName}`,15,y);

    y += 8;

    doc.text(`Report Date: ${record.rawRecord.reportDate}`,15,y);

    y += 15;

    y = this.addSummary(
        doc,
        record.summary,
        y
    );

    autoTable(doc, {
      startY: y,

      head: [[
        "Test Name",
        "Value",
        "Unit",
        "Reference Range",
        "Status"
      ]],

      body: (record.rawRecord.results ?? []).map((r: any) => [

        r.testName,

        r.value,

        r.unit,

        r.normalRange,

        r.status

      ]),

      theme: "grid",

      headStyles: {
        fillColor: [52, 152, 219]
      },

      styles: {
        fontSize: 10,
        cellPadding: 3
      }
    });

    this.addFooter(doc);

    doc.save(`${record.labName ?? 'lab-report'}.pdf`);

}
private async generateImagingPdf(record: any) {

  const doc = new jsPDF();

  let y = await this.addHeader(
    doc,
    "Imaging Report"
  );

  doc.setFontSize(12);

  doc.text(
    `Imaging Type: ${record.rawRecord.imagingType ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Body Part: ${record.rawRecord.bodyPart ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Doctor: ${record.rawRecord.doctorName ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Report Date: ${record.rawRecord.reportDate ?? "-"}`,
    15,
    y
  );

  y += 15;

  if (record.summary) {

    y = this.addSummary(
      doc,
      record.summary,
      y
    );

  }

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");

  doc.text("Findings", 15, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const findings = doc.splitTextToSize(
    record.rawRecord.findings ?? "-",
    180
  );

  doc.text(findings, 15, y);

  y += findings.length * 6 + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);

  doc.text("Impression", 15, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const impression = doc.splitTextToSize(
    record.rawRecord.impression ?? "-",
    180
  );

  doc.text(impression, 15, y);

  this.addFooter(doc);

  doc.save(
    `ImagingReport-${record.rawRecord.imagingType ?? "Report"}.pdf`
  );
}

  private async generatePrescriptionPdf(record: any) {

  const doc = new jsPDF();

  let y = await this.addHeader(
    doc,
    "Medical Prescription"
  );

  doc.setFontSize(12);

  doc.text(
    `Doctor: ${record.rawRecord.doctorName ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Patient: ${record.rawRecord.patientName ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Prescription Date: ${record.rawRecord.prescriptionDate ?? "-"}`,
    15,
    y
  );

  y += 15;

  if (record.summary) {
    y = this.addSummary(
      doc,
      record.summary,
      y
    );
  }

  autoTable(doc, {
    startY: y,

    head: [[
      "Medicine",
      "Dosage",
      "Frequency",
      "Duration",
      "Notes"
    ]],

    body: (record.rawRecord.medicines ?? []).map((m: any) => [

      m.medicineName ?? "-",

      m.dosage ?? "-",

      m.frequency ?? "-",

      m.duration ?? "-",

      m.notes ?? "-"

    ]),

    theme: "grid",

    headStyles: {
      fillColor: [52, 152, 219]
    },

    styles: {
      fontSize: 10,
      cellPadding: 3
    }
  });

  this.addFooter(doc);

  doc.save(
    `Prescription-${record.rawRecord.patientName ?? "Report"}.pdf`
  );
}
private async generateMedicineBoxPdf(record: any) {

  const doc = new jsPDF();

  let y = await this.addHeader(
    doc,
    "Medication Record"
  );

  // Medicine Information
  doc.setFontSize(12);

  doc.text(
    `Medicine Name: ${record.rawRecord.medicineName ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Dosage: ${record.rawRecord.dosage ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Frequency: ${record.rawRecord.frequency ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Duration: ${record.rawRecord.duration ?? "-"}`,
    15,
    y
  );

  y += 8;

  doc.text(
    `Source: ${record.rawRecord.source ?? "-"}`,
    15,
    y
  );

  y += 15;

  if (record.rawRecord.notes) {

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);

    doc.text("Notes", 15, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const notes = doc.splitTextToSize(
      record.rawRecord.notes,
      180
    );

    doc.text(notes, 15, y);

    y += notes.length * 6 + 10;
  }

  this.addFooter(doc);

  doc.save(
    `Medicine-${record.rawRecord.medicineName ?? "Record"}.pdf`
  );
}
}